### ISSUE TITLE
Library: Show dats as "children" of the sites that created them?

### ISSUE THREAD

**Issue by BurningPixels** [beakerbrowser/beaker#1002]
Operation System: mac os
Beaker version: 0.8.0 prerelease 5

Hey it's kinda anoying that for example if i create an photo album in your photo app it creates a whole new site. i know that it has to be but why is it a complete new site in the library? What about sort it like i have the big app the photo app and if i create an album the album site is "under" the photo app in the library with and fold thing.

**Comment by taravancil** [comment]
Yeah that's just one way to create a photos app. You could also build one that keeps the albums in the original website. That was a design choice that allowed each individual album to be shared secretly without visitors being able to see all the other albums.

As far as having child websites in the Library, that's not something we can do easily. We'd have to come up with a way for sites to specify which site is their parent, and then expect that all websites will follow the convention we specify. Doable, but will require a lot of hard thinking about how to do that so it's generic enough for everyone.

**Comment by pfrazee** [comment]
I'm going to keep this issue open as a UX discussion. I don't know what the timeline will be, but it's an idea worth keeping in mind.

**Comment by webdesserts** [comment]
In this particular case, this could be solved with the "data dat" concept y'all had previously explored, rather than a full "child archive" concept. For example, if "data dats" were a thing, these archives could be filtered out of your default library view so they wouldn't clutter the library UI as you created them en masse. It should also be easy to then display a list of all data archives that a given site has write access to.
