### ISSUE TITLE
I can't seem to download anything,

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/beaker#1123]
Operation System: Mint 18.1
Beaker version: Uncertain, internet wont load it.

I'm not noticing with Beaker browser in particular, if I start an important download, I'm not able to recontinue that download, I pretty much have to start all over. This is tedious for downloads that are as big as say, Kiwix and Scuttlebutt, which the entire point is for them to be offline, until you sync up with the internet.

Do other browsers have this issue, or is this a Beaker thing?

**Comment by Butterfly** [comment]
*waving* I'm "just" a user... who actually has never been able to get Beaker to work.. actually. :smile:

BUT I can give feedback on this. Almost all browsers, if not all, have this problem. ONCE in a while you can find a plugin that compensates.

Otherwise.. You said you're using Mint.. Do you have access to anything like `wget`? I LOOOOVVVVE `wget`!

Just as example, I'm on dialup and am in finishing stages of downloading approximate 380MB of a new operating system, [Linux From Scratch](http://www.linuxfromscratch.org/), with barely a burp today.

You can stop and start `wget` at user's choice...

AND sometimes it will still keep going even if the *Internet* burps and interrupts your download. You do that by using this terminal command line:

`wget -c /path/to/desired/online/file`

That `-c` tels `wget` to **_c_**ontinue if it's interrupted by the Internet connection. CTRL+C is the user's way of manually interrupting if necessary.

Hope this helps someone, if not in this specific case. :smile:

**Comment by pfrazee** [comment]
@LWFlouisa Is the issue that you're downloading large files on a bad connection, the connection drops, and you can't finish the download?

**Comment by pfrazee** [comment]
Closing because this doesnt seem like a Beaker issue
