### ISSUE TITLE
npm start Beaker issue

### ISSUE THREAD

**Issue by katyannflowergirl** [beakerbrowser/beaker#1149]
Operation System: LMDE 2
Beaker version: 8.0

```
gulp start

[03:12:30] Using gulpfile ~/Desktop/beaker/gulpfile.js
[03:12:30] Starting 'start'...
[03:12:30] Starting '<anonymous>'...
Spawning electron /home/user/Desktop/beaker/node_modules/electron/dist/electron
[03:12:31] The following tasks did not complete: start, <anonymous>
[03:12:31] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beakerbrowser@ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beakerbrowser@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by pfrazee** [comment]
@iwwmidatlanticgdc are you building from source? Did you follow the build instructions? https://github.com/beakerbrowser/beaker#building-from-source

**Comment by iwwmidatlanticgdc** [comment]
yes but I am randomly encountering this issue when i type 
```
npm start
```
in terminal. Sometimes it works perfectly, other times it works for a bit then crashes, and other times it gives me the error above.

**Comment by iwwmidatlanticgdc** [comment]
nope

**Comment by pfrazee** [comment]
Okay, I wonder if this is unrelated to how you're starting the process. I wonder if Beaker is just crashing.

**Comment by Michael-S** [comment]
I hadn't updated Beaker in a while, but I updated it this week and I'm getting the same error.   The actual error is in the 'npm run rebuild' step.  I've attached a debug log of the error I'm seeing.  I've tried two different versions of node and npm and gotten the same errors.  I'm on the master branch.  
[2018-10-21T13_31_24_170Z-debug.log](https://github.com/beakerbrowser/beaker/files/2499170/2018-10-21T13_31_24_170Z-debug.log)

**Comment by Michael-S** [comment]
Oh, sorry to double-comment but I see some of the errors from the command are not included in the debug log.  I presume these are relevant:  
--------------------- begin errors, comments preceded with ------
leveldown@1.9.0 install /home/mswierczek/beaker/app/node_modules/leveldown
> prebuild-install || node-gyp rebuild

/home/mswierczek/beaker/app/node_modules/node-abi/index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 3.0.4 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

------ somewhat further down it has this error, presumably (?)
------ related to the first one
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
---------------------- end content

**Comment by pfrazee** [comment]
> I updated it this week and I'm getting the same error. The actual error is in the 'npm run rebuild' step

That means it's not the same error! Can you open a separate issue?

**Comment by Michael-S** [comment]
Sorry, I thought the error that iwwwmidadlanticgdc reported from 'npm start' is identical to mine, but when I did a closer comparison it was not.  I apologize, I'll file a separate issue.

**Comment by pfrazee** [comment]
All good!

**Comment by Michael-S** [comment]
Just to follow up, running 'npm run burnthemall' and then the normal steps fixed everything for me.   So of course I won't be opening another issue.

**Comment by pfrazee** [comment]
Good to hear!

**Comment by sindhu544** [comment]
plz suggest us when starting npm to launch beaker browser the below error displaying
npm start

> beakerbrowser@ start /home/pi/beaker
> gulp start

[06:53:08] Using gulpfile ~/beaker/gulpfile.js
[06:53:08] Starting 'start'...
[06:53:08] Starting '<anonymous>'...
Spawning electron /home/pi/beaker/node_modules/electron/dist/electron
/home/pi/beaker/node_modules/electron/dist/electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /home/pi/beaker/node_modules/electron/dist/electron)
[30795:0304/065308.697701:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/pi/beaker/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
[06:53:08] The following tasks did not complete: start, <anonymous>
[06:53:08] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beakerbrowser@ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beakerbrowser@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-03-04T06_53_08_716Z-debug.log

**Comment by sindhu544** [comment]
please let us know the launching process of beaker browser 
when iam trying from debian, internet->beaker browser its showing the error as
Failed to execute child process "/usr/bin/beaker-browser" (Not a directory)
