### ISSUE TITLE
Warn user before navigating away from an unsaved file in library

### ISSUE THREAD

**Issue by yihangho** [beakerbrowser/beaker#1173]
Operation System: macOS 10.13.6
Beaker version: v0.8.0-prerelease.9

I use the library and its editor to write some notes. I think it will be useful if it gives a warning (e.g., "You have unsaved work. Are you sure you want to leave this page?") before navigating away from the editor when there are unsaved changes.

This is probably not a bug, but I think it is a nice enhancement, especially given that I just accidentally swiped to the previous page before saving what I wrote. ☹️

PS: Also not sure if this issue belongs here or one of the other repos under this org.

**Comment by pfrazee** [comment]
Hi! Yes this is the right repo, and yes I think this would be a good idea! Added to my todos.

**Comment by RangerMauve** [comment]
OMg! This has happened to me before. I wrote a few paragraphs for a blog post and reflexivly used `ctrl+[` to shrink the margin which navigated away and made me lose all my changes. 😭

**Comment by Septimus** [comment]
Would an auto save feature be a good choice here? If not by default, make it a user toggled option? 

I mean this in addition to the prompt as well! :)

**Comment by yihangho** [comment]
@Septimus I think that's a good idea, perhaps instead of auto save into the dat archive, but to some local storage-like thing. When something goes horribly wrong, Beaker can then offer to recover from local storage.

@pfrazee Will you be working on this any time soon? If not, I'm happy to give this a try some time this weekend.

**Comment by pfrazee** [comment]
For now let's just do the prompt to keep the task simple.

@yihangho Feel free!

**Comment by Butterfly** [comment]
> Would an auto save feature be a good choice here? If not by default, make it a user toggled option?

I love auto save on various things, e.g. office software, too. Am just chiming in with an observation regarding default versus not. I've had to turn that feature off (in other programs) because I'm a very low income level user with extremely limited resources.

In other programs, that feature is/was a memory hog. If auto save existed by default and a user didn't know it was on (AND the feature was a momentary memory hog by innate nature), I could see someone not realizing that was the case in such a way that Beaker would stand the potential for getting dissed for being an overall resource hog... when that was NOT the real case at all.

Does that make sense in the way that it's meant to help maintain an always positive perception of Beaker?

If the Developer Choice becomes that auto save is not on by default, I'm then wondering out loud: How would you go about making *happy dance* that this *fabulous* option is available if users want to enable it?

It's such a good idea because power failures happen... computer ghost and ghoulies happen. A safety backup that helps prevent having to recreate an entire heartfelt, already deep in progress project is a *really nice perk* to know exists in a software package. #ThankYou for thinking of it! :smile:
