### ISSUE TITLE
Don't let this become another obscure browser

### ISSUE THREAD

**Issue by tiotrom** [beakerbrowser/beaker#1176]
I've seen many kinds of examples about how we can create a better internet through this or that browser and I have seen these projects fail. I really love the concept behind beaker browser but in my honest opinion it can never take off. Try to beat Chrome or Firefox... So, from a layman perspective in terms of how this tech works, here's what would make me or lots of other people adopt this tech: make it as an extension of sort that can work with Chrome and Firefox. So that I can simply install on my Firefox or Chrome, and then can access DAT urls. Then give me more control over that through the extension's options (like to publish my website or share files).

I am motivated enough to install and set up Beaker browser, but I am sure most people won't. They use the browser as a window to the Internet and if they lack easy support from extensions that most need (like adblockers, password managers, and the like) then they won't use another browser. Look at Brave browser and other browsers that enabled torrenting as default and other stuff. They are virtually unknown.

I hope you take my comment as constructive and I surely will use Beaker browser since I want to make some decentralized websites and share files.

**Comment by RangerMauve** [comment]
Hi Tiotrom.

I'm not directly affiliated with Beaker, but I've been in the Dat community for a while so I think I could help explain some stuff.

As it stands, browsers don't have enough APIs for us to build everything we need in order to make Dat work in them.

Currently, Mozilla is leading the way in provoding APIs to browser extensions for faciliating p2p protocols in the form of the [libdweb](https://github.com/mozilla/libdweb) library for Firefox Nightly.

As it stands, the state of the art in Dat extensions is currently [dat-webext](https://github.com/cliqz-oss/dat-webext) which supports loading content over Dat and has a lot of support for the DatArchive API in JavaScript.

Chrome is following behind Mozilla with introducing one of the most important APIs to get this stuff started, the `registerProtocolHandler` API. The conversation right now is [whether there should be a more relaxed allow-list, or a small block-list](https://github.com/whatwg/html/issues/3998) for this API.

Ones this API is available in more browsers, we'll be able to start loading `dat://` URLs seamlessly in a web page.

This won't enable us to do the actual peer to peer communication, however, so more effort will be needed for that.

In the meantime, Beaker is important in that it demostrates to tech people that this technology is useful and can help convince browser vendors to enable the APIs we need to take it further.

I think that the end goal is that major browsers will support loading `dat://` URLs without having to install any extra plugins.

**Comment by sgwilym** [comment]
Even if the end goal of Beaker is 'just' to push major browsers into supporting dat URLs, it has tremendous value in demonstrating how to build interfaces and experiences for p2p conventions, e.g. showing the number of peers in the URL bar, the seeding dropdown, and dat publishing tools.

**Comment by roscoevanderboom** [comment]
I think people simply haven't figured out the potential of a browser like Beaker. It's not just being able to view dat:// sites, it's the ability to generate a web page within a minute, publish and share it with selected people. Just use an instant messenger that allows you to share the link in a private( encrypted chat) or public way (Facebook group).  I just use Riot webapp in Beaker. Then a link simply loads in a new tab.

Currently, there is just the basic website template to choose from, but in time, I imagine being able to generate a more complex webpage/site, i.e. a social media page, or a work portfolio page. And seeding websites is a great way to distribute content. 

I think it has great potential. I do need some spell checking integration....

**Comment by tiotrom** [comment]
Hi guys. I am very happy to read your responses. I totally understand your points. I think Beaker is an amazing initiative and I plan to use it. However you should consider to make this more "mainstream" somehow, maybe as I said to try and integrate to existing browsers or try to make Beaker browser compatible with all Chrome's extensions. I for one cannot use it as my daily driver since I don't have the flexibility of addons/extensions. I've seen a similar approach with ZeroNet https://github.com/HelloZeroNet/ZeroNet and I feel like it kinda went underground and I am afraid Beaker won't have that much traction to "stay in the game" unless it makes the browser more than a simple browser dedicated to p2p. Cheers!

**Comment by taravancil** [comment]
Hi @tiotrom, appreciate the suggestion, but like @RangerMauve said, mainstream browsers don't currently offer the tools we need to integrate a fully-fledged p2p browsing experience. We're not trying to be the daily driver for millions of people, we're a very small team trying to demonstrate what new capabilities a p2p protocol can provide to a browser.

**Comment by h3298** [comment]
> **I really love the concept behind beaker browser but in my honest opinion it can never take off.**

For development, testing & demonstration purposes, I think it is important to have a dedicated dat:// browser.  But I have the same concerns and the same feeling: this is not a browser the general public will use every day, because you cannot customize the extensions or the interface.  There are so many fundamental UI bugs, and so much effort is being duplicated here:

> **try and integrate to existing browsers or try to make Beaker browser compatible with all Chrome's extensions.**

Just look at the Brave browser -- the developer branch is now supporting Chrome extensions, and many user interface issues that Beaker struggles with have already been addressed.  Why not just modify Brave as needed, instead of re-inventing the browser from scratch.

https://github.com/brave/browser-laptop
https://github.com/sindresorhus/awesome-electron

**Comment by tiotrom** [comment]
Any recent thoughts on this? Wouldn't it be awesome to have access to Firefox's addons? :) This is such an amazing project but it means users have to use two browsers in order to say block ads and such.

**Comment by RangerMauve** [comment]
You can get a lot of the Dat functionality / the new hyper protocol in the [Dat-Webext](https://github.com/cliqz-oss/dat-webext) firefox extension.

it doesn't have all the fancy editing tools that Beaker has, but it can load sites and isn't too hard to extend if you want to add stuff.

**Comment by pfrazee** [comment]
There's another thread on extensions.
