### ISSUE TITLE
rename method doesnt only rename

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1186]
Operation System: windows 7
Beaker version:  Beaker v0.8.0-prerelease.9

await archive.rename( '/folder/new.json', '/folder/new2.json' ) ;

I tried several times to rename a file but the rename method doesn't rename the file,it just creates new copy of the file with the requested name.

**Comment by pfrazee** [comment]
Thanks for reporting.

The rename process works by copying the files and then deleting the old ones. It has to do that because hyperdrive has no concept of renaming internally. (cc @mafintosh- would there be any benefit to adding it?)

It sounds like Beaker is failing on the delete step for some reason. I'll investigate.

**Comment by arni077** [comment]
@pfrazee is it how webDB works? When you try to update a property on a json file,webDB actually creates new updated file then delete the old one?

**Comment by pfrazee** [comment]
No, webdb simply overwrites the files. The process I described is for file moves only

**Comment by pfrazee** [comment]
I'm not able to reproduce this. Can you tell me more about what happened? Were you syncing to a local folder? Was preview-mode on?

**Comment by arni077** [comment]
1.yes
2.preview wasnt on

**Comment by arni077** [comment]
No.
