### ISSUE TITLE
When Beaker is running, _sometimes_ some shortcuts stop working on _other_ programs

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1189]
Operation System: Ubuntu 16.04
Beaker version: Latest-source (0ccd1d50883fba2499641da97447a5a07011e0e6)

## Problem Description

When Beaker is running, sometimes some keyboard shortcuts stop working (e.g., Ctrl+F) on _other_ programs.

## How Beaker is involved

- According to [this answer](https://askubuntu.com/a/926156/725387), any electron app that uses [electron-shortcut](https://github.com/parro-it/electron-localshortcut) might be involved.
- I had Beaker running when the problem was happening. I closed Beaker and the problem went away immediately.

## Suggested Solution

Probably bumping [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) to `2.0.0` should solve it, according to parro-it/electron-localshortcut#16. **Note**: Didn't investigate enough to know if there're other implications.

**Comment by pfrazee** [comment]
@hossameldeen okay thanks very much for reporting and doing that research, added to my TODOs

**Comment by Septimus** [comment]
Not getting the issue on macOS High Sierra v10.13.6. If any other mac users want to confirm with maybe a different version or something do let me know. I did "cmd + F" with beaker opened and everything appeared to work in FireFox and Chrome as expected.

Will be testing on Linux later tonight or tomorrow to find a fix.

**Comment by pfrazee** [comment]
@Septimus I have a linux box so I can test this. I'll try to reproduce, and if I can, it's easy to bump that dep and test.

**Comment by pfrazee** [comment]
I couldn't reproduce but I bumped electron-shortcut to 3.1.0

**Comment by hossameldeen** [comment]
After the update to 3.1.0, no shortcut seems to be working (e.g., Ctrl+number). v2.0.2 seems to be [the latest release](https://github.com/parro-it/electron-localshortcut/releases) and [v3 seems to be still problematic](https://github.com/parro-it/electron-localshortcut/issues/46).

I've tried v2.0.2 and shortcuts that use `electron-localshortcut` seem to be working (e.g., Ctrl+number). However, Ctrl+F doesn't work.

In both versions, the OP bug doesn't seem to be there. It's indeed random and doesn't always happen, but I noticed it usually happens with minimization and switching between applications. Anyway, it doesn't _seem_ to be in v3 or 2.

**Comment by Butterfly** [comment]
This is me being very naive because I still haven't been able to get an instance of Beaker running, and I've been following you all for *quite a while* now. :smile:

I'm understanding that you all can access regular websites. If no, I'm sorry, I'll just keep trying to get Beaker installed so I can see what it actually does and does not do.

If yes, you access the entire Internet, could someone please consider trying shortcuts while on Twitter? I've thought about this A LONG time before asking, BUT I'm experiencing very similar to what you're describing, just with another browser: Shortcuts stop working. The difference for me is shortcuts stop working within the (a different) browser. My case does *not* affect non-browser programs.

My thought process in choosing to say this out loud is that maybe if Twitter blocks shortcuts for you all *inside* of Beaker, too, maybe that leads to one more clue about what's going on. Or not... but here's hoping that it does! :smile:

**Comment by pfrazee** [comment]
Yeah I'm noticing that some shortcuts stopped working with the upgrade. I'll dig into it more, maybe try v2.

**Comment by hossameldeen** [comment]
The problem just occurred with me with v2.0.2. Still on the same Beaker commit as I was in the OP.

With the things as they are, I know neither a solution nor reproducible steps for the bug :(

**Comment by pfrazee** [comment]
I had to rewrite [electron-localshortcut](https://github.com/beakerbrowser/electron-localshortcut) to support webviews. *Should* be working now on all platforms.

**Comment by pfrazee** [comment]
Going to assume this is fixed, please reopen if not.

**Comment by hossameldeen** [comment]
Chapeau!

Confirmed. Will reopen if happens again.
