### ISSUE TITLE
Can't Copy URL

### ISSUE THREAD

**Issue by psych0fred** [beakerbrowser/beaker#1240]
Operation System: Windows 7
Beaker version: .8

Just reinstalled after Beaker failed to launch and it launches, but I tried to copy a URL from the address bar to put fritter on my speed dial/new tab page but using the right click menu to copy and paste the URL failed. Using ctrl-C worked, just not right-clicking and selecting copy.

**Comment by pfrazee** [comment]
Thanks for reporting, I'll check into it.

**Comment by parfish** [comment]
Confirmed - was just going to post this bug (exactly as above, including same OS and Beaker v0.8.0 as OP).

Though it's not just URLs from the address bar, it's any content (i.e. body text) - right click + copy is not copying to clipboard, so whatever was in the clipboard is pasted instead, but Ctrl+C does copy to clipboard. 

Hope that convoluted mess helps rather than hinders,  

Cheers, 
P.

**Comment by pfrazee** [comment]
Looks like an electron issue: https://github.com/electron/electron/issues/15219

These folks came up with a pretty simple solution, just use your own click handlers instead of relying on Electron's "role" tool: https://github.com/vladimiry/email-securely-app/issues/49. We can do the same.
