### ISSUE TITLE
New tabs won't open second time

### ISSUE THREAD

**Issue by psych0fred** [beakerbrowser/beaker#1241]
Operation System: WIndows 7
Beaker version: .8

When clicking on a link that targets a new tab, the first time the link is clicked on a new tab opens and the page loads as expected. After closing the tab and clicking on the same link a second time, no tab opens and no page loads. This was on an http page.

**Comment by psych0fred** [comment]
I was trying on http://www.secretsociety.com 
I saved the page locally and the same problem occurred, so it's got it to be the page or the browser. 
The page is basic html with targets, no javascript. 
Maybe the doctype?

**Comment by Septimus** [comment]
I'm at least not getting the problem on macOS 10.14

psyco0fred, I am assuming that you are able to visit http://www.secretsociety.com/ but when you try to click on a link from that site you are experiencing the stated problem?

**Comment by Septimus** [comment]
Alright so it looks like the issue is the website is using:
`<a href="" target="framename"></a>` 

Should be: 
`<a href="" target="_blank"></a>`

Unless the intended use of the website is to open inside an internal <frame> element but I don't believe this is not supported/intended use in HTML5

**Comment by psych0fred** [comment]
I've never experienced the problem before but it's easy enough to fix, it's just old code.  I guess I'll have to find a better HTML validator. Thanks!

**Comment by paul90** [comment]
@psych0fred - can you please reopen this, it is an error. 

`target` is defined, in HTML5, as:
> The target attribute, if present, must be a valid browsing context name or keyword. It gives the name of the browsing context that will be used. User agents use this name when following hyperlinks. [source](https://www.w3.org/TR/html50/links.html#attr-hyperlink-target)

And, a valid browsing context and it's effects, are defined in by the table in the [browsing context names](https://www.w3.org/TR/html50/browsers.html#valid-browsing-context-name-or-keyword) section of the spec.

I have created a little dat with some simple tests dat://9a83f2cc439588099caa436953a3cd66351d53464f5b925ed1f4e880d9c86bfa/ or to compare with different browser https://browser-context-test-paul90.hashbase.io/

N.B. There is a test on `page2.html` that tries to reuse the `page1` context - in Beaker this will open a new tab rather than reuse an existing context.

**Comment by paul90** [comment]
Just managed to test this with an old version of Beaker (0.8.0-prerelease.7) on Windows 10, and it works as expected - in that closed tabs get reopened when a link targets them.

**Comment by Septimus** [comment]
@paul90 I've been working on this all morning. Did you also test (from your test site) that the second set of links opens into the correct context?

Like if I open `page1.html`
Then I click the link for `also1.html`
And it opens inside of the currently opened `page1` context?

**Comment by paul90** [comment]
So, on `page1.html` the second `also1.html` link targets the `page1` context. 

With Beaker, both the 0.8.0 prerelease and release version, it will open that page in a new tab.
With Chrome, Firefox, or Safari, it works as I would expect and does not open a new tab.

I notice that in Beaker that `window.name` is `null` - it should be set to the name of the browsing context. If I set the name manually it will open in the same tab, as expected, rather than open a new one.

The `also1.html` link on `page2.html` will still open in a new tab - I remember seeing a similar issue with an old version of Firefox or Chrome (I forget which).

**Comment by pfrazee** [comment]
Yeah I can confirm, I'm seeing some incorrect behaviors here.
