### ISSUE TITLE
Open tabs are not restored after crash

### ISSUE THREAD

**Issue by kekukui** [beakerbrowser/beaker#1254]
Win64 / Bug - Pages are not restored after crash

Lost several days work.
  **WARNING SHOULD APPEAR AT BROWSER LAUNCH THAT CRASH RECOVERY IS BROKEN !!!!!**

**Comment by pfrazee** [comment]
Can you explain a little bit about what you lost, just so I know the concern? Was it some text buffers that hadn't been saved?

**Comment by pfrazee** [comment]
Ah. Very sorry to hear that, I'll look into it.

**Comment by h3298** [comment]
I've had some time to think about this, and here is what I want to add:

On my Windows box I have a fixed size swap file - partly to avoid fragmentation, but also because I would rather crash an application than get to a point where disk thrashing makes it difficult to regain control of the machine.  And poorly designed extensions or web sites can contribute to that problem.  I have tested all of the major Chrome based browsers and pushed them to the point of crashing on various occasions, but never lost any work.  So it came as a big shock and surprise when I lost the entire session on Beaker, and I felt like the user ought to be warned in advance if the crash recovery feature is known to be broken.
