### ISSUE TITLE
`npm start` hangs on linux from broken electron 3

### ISSUE THREAD

**Issue by substack** [beakerbrowser/beaker#1270]
I'm on debian 9. After `npm run burnthemall` beaker hangs at `npm start`:

```
$ npm start

> beakerbrowser@ start /home/substack/projects/beaker
> gulp start

[16:37:52] Using gulpfile ~/projects/beaker/gulpfile.js
[16:37:52] Starting 'start'...
[16:37:52] Starting '<anonymous>'...
Spawning electron /home/substack/projects/beaker/node_modules/electron/dist/electron
[ dat-daemon ] Starting...
```
I ran into this behavior recently with another electron app and downgrading to version 2 fixes the issue.

**Comment by pfrazee** [comment]
Is it possibly related to https://github.com/electron/electron/issues/13415 ?

**Comment by Michael-S** [comment]
@substack   - Beaker broke for me a month or two back on Debian Sid (Unstable) and the default node package.  I switched to downloading the release stable binaries from nodejs.org and everything worked fine.

**Comment by asoplata** [comment]
I get this same thing on Debian Stable; even though the versions are different, the issue might be https://github.com/electron/electron/issues/12850 . I could get Beaker to start only by running

```{bash}
npm start > /dev/null
```

Based on very little evidence, I *think* this may be an Electron problem instead of a Beaker problem. HTH

**Comment by alexandre1985** [comment]
If you use the AppImage beaker's version it won't have this issue.
It is the best choice
