### ISSUE TITLE
Unaccessible content while someone is seeding

### ISSUE THREAD

**Issue by raphaelbastide** [beakerbrowser/beaker#1284]
Operation System: MacOS, Linux, Windows
Beaker version: Many

Today I was in class with my students and everyone  published a page using Beaker’s “Create new from folder”. Once published, only a couple of dat URL were accessible to some of the people in the class (not all). As far as I can remember, once a content is public, anybody can connect to it directly? Why do we get the “Add to watchlist” page?

- Everybody has Beaker open so seed actually existed
- I personally checked if the web project were “published”
- This is not the first time I meet this issue, I already had to wait hours before a friend could access my newly made dat site.

Is this a known issue?

**Comment by pfrazee** [comment]
That's a shame. It sounds like you were all on the same LAN, yes? I wonder if we have a LAN discovery issue. Is there any chance the LAN would be hostile to multicast traffic?

**Comment by raphaelbastide** [comment]
Same LAN: Yes we were. The school’s.
> Is there any chance the LAN would be hostile to multicast traffic?
I have no idea. I can make some tests next time. How can I do so? Can hashbase help to solve that temporarily?

**Comment by pfrazee** [comment]
Yeah, Hashbase can help by being generally more reliable. There's a really good chance the school is blocking the multicast traffic. We just haven't had the resources to work around that scenario.

**Comment by raphaelbastide** [comment]
Good to know. I will use Hashbase next time. Thanks!

**Comment by pfrazee** [comment]
Yeah. Sorry for the issues!

**Comment by raphaelbastide** [comment]
I would like to come back to this. We made an experiment with a friend, he is remote. We both have an up to date Beaker, mine on linux, his on Mac. I publish a file, send him the URL directly by chat, both of our Beaker are opened. He receives nothing. Same if he publishes something. Nothing appears to me: the URL shows the “Add to watchlist” page. However, if I use Hashbase to add my hash, not only Hasbase can download it, but my friend can access it less than a minute after this addition.
It seems that our nodes can’t find each other. What do you think? Can it be more a dat related problem? If yes, should we forward a particular port ? Thank you in advance!

**Comment by pfrazee** [comment]
@raphaelbastide I love the server.

This is a dat-related problem. You can break down Dat into roughly three different domains:

 - Peer discovery (sometimes called the "discovery network")
 - Connection establishment (often grouped into the "discovery network")
 - Data structures (the core of Dat's novel work)

If I had to rank those by the amount of resources we have been able to allocate, connection establishment gets the very least attention. This is just because of the huge list of priorities we have and the limited resources.

If you're connecting over the WAN, then it's likely that the peers are aware of each other but just can't punch through their networks. We have some improvements on the roadmap (such as leveraging UPnP) but just haven't had time to implement them.

**Comment by da2x** [comment]
@raphaelbastide, multicast wouldn't happen to be disabled on your school network? It's not uncommon for that to be disabled on networks with thousands of machines because then the IT department can cheap out on switches and wireless access points.

For future classes, you can bring a regular wireless router next time. Don't connect it to the school's network and just ask students to connect to the router's access point. They won't reach the internet but they should be able to see each others websites and work around network policies that might be blocking Beaker. Can use it as an opportunity to discuss how something like peer-to-peer networking can work on an ad-hook network and why it makes it so hard to censor.

**Comment by raphaelbastide** [comment]
I doubt it is related to the school networks, I also made tests with “normal” internet acces and I still have this problem. Right now I am giving a dat / beaker workshop in Brussels and students can’t acces my pages, I can’t neither access theyrs, wich puts me in a really akward situation.

For example, an archive `dat://c1d28dff64c0d723c899777ad7f74d06815dfef0918348f6bdbb3a4905b39227` for example, is both on my machine, seeded by a server in germany, and should be on hasbase too, but only one student on a group of 5 can access it. I am confused.

@da2x your idea of a local network could be nice but showing that the publication on dat is not local only is a really important point for me.
