### ISSUE TITLE
DatArchive.history off-by-one error

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1293]
Operation System: Ubuntu 16.04
Beaker version: b951fa610ba89d5e987d96a3182e9c6360a6f09e

**Examples:**
- `await (new DatArchive('dat://beakerbrowser.com')).history({start: 0, end: 1})` returns an empty array.
- `await (new DatArchive('dat://beakerbrowser.com')).history({start: 0, end: <history real length>})` returns `<history real length -1>`.
- `await (new DatArchive('dat://beakerbrowser.com')).history({start: 0, end: <history real length + 1>})` returns `<history real length>`.

**Strange behaviour:**
- `await (new DatArchive('dat://beakerbrowser.com')).history({start: 0, end: <0 or -1>})` returns full array.

**Undefined? behaviour:** (not really a problem)
- `await (new DatArchive('dat://beakerbrowser.com')).history({start: 0, end: <anything < -1 or > history real length + 1>})` times out.

**Last? related commit:**
- beakerbrowser/beaker-core@5167019173fcb407986fe4dc0f33ff4c1ad111b6 -- wish I could solv it but unfortunately I don't know the layers below. Also, not implying that the behaviour was correct before this commit; idk.

**Checklist:**
- Made sure `app/node_modules/beaker/core/package.json` has version `3.0.1`.

**Comment by pfrazee** [comment]
I've noticed this too. The `history()` call is basically a call to the metadata hypercore's [createReadStream()](https://github.com/mafintosh/hypercore/blob/master/index.js#L1031) call.

@mafintosh What @hossameldeen is pointing out is true of hyperdrive's `history()` method and probably true of hypercore's `createReadStream()` call. It basically seems like hypercores are 1 indexed rather than 0-indexed. WDYT?

**Comment by mafintosh** [comment]
@pfrazee hypercore's are 0 indexed in all methods. prob the initial header making things weird in some api

**Comment by pfrazee** [comment]
@mafintosh ah I bet that's what that is. Hmm. I'll have to think about that: should the hyperdrive abstraction hide that? 🤔
