### ISSUE TITLE
Inconsistent Keyboard Shortcuts

### ISSUE THREAD

**Issue by evan-evone** [beakerbrowser/beaker#1297]
Operation System: `macOS 10.13.6`
Beaker version: `v0.8.2`

At times, keyboard shortcuts (such as `cmd`-`shift`-`{`/`}` to switch tabs and `cmd`-`F` to find) will work exactly as expected. However, at other times, they won't work at all, and I need to go to the toolbar to carry out the functions. These are the keyboard shortcuts given in the help menu, so it is weird that they will only work some of the time.

I don't know if there's something I'm missing, or if there's an actual bug that needs to be fixed, but any help would be appreciated!

**Comment by Butterfly** [comment]
A humble observation from "just a normal user" here.. This topic comes up every once in a great while so there are a small number of prior issue reports that *might* help:

[shortcut related issues in beakerbrowser/beaker](https://github.com/beakerbrowser/beaker/search?q=shortcuts&type=Issues)

Not all of those issues are titled specifically about "keyboard shortcuts", but I didn't want to cull and thus possibly skip something that might indirectly help anyway.

You know what, I just looked at that list very quickly. That list reminded me about #1189 (When Beaker is running, _sometimes_ some shortcuts stop working on _other_ programs).

Coincidentally, someone just mentioned Xine (`xine-ui` Linux video player) over at Debian-User so that genre of packages was super fresh in mind. Speaking from personal experience, some programs like that use "{" and "}" to speed up and slow down video playback speeds........ so... *hm* regarding a (keyboard mapping??, keyboard key assignment) conflict that might cause the sporadic works/doesn't works aspect of your issue. :smile: 

Typing *that* out caused me to think a good question for whenever this pops up is: What other programs are open when the shortcuts **don't** work, and what other programs are open when the shortcuts **do** work?

As an aside, I've always a-sumed that keyboard shortcuts were intrinsically *only* about the program within which they were being applied at any given second. It never once crossed my mind that there might be something deeper going on under the hood with respect to software interactivity. At the end of every day, all those open/not open packages *are* simultaneously bound to that one single keyboard that's taking its cues from all over the place all the time. :smile: 

Anyway.. If one or more of those previous issues sound similar to what you're experiencing, you could reference them with respect to your own issue to help speed up the debugging process for the Developers. :smile:

**Comment by evan-evone** [comment]
Checking the open application was a good thought, but I just tried it and saw the same results, so... no luck.

Additionally, this same keyboard shortcut always works in Google Chrome, regardless of what I have open, so I doubt it's a shortcut conflict.

---

**For Clarity**: When I say the keyboard shortcuts are "sporadic," I don't just mean that the shortcuts only work sometimes. I mean that they'll work two or three times in a row, then suddenly stop working - I won't have left beaker or anything like that, they just stop, and then start again.

- E.G. if I have 5 tabs open, and I'm on tab 1 and want to get to tab 5, I would normally do `cmd`-`shift`-`}` 4 times, but in beaker, it might let me advance one tab and then refuse to let me advance further.

---

I did some searching before I opened this issue, but found nothing directly related to my problem. I didn't, see, however, #1219, which is focused mostly on `cmd`-`f` (`ctrl`-`f`, in that case), but also seemed to indicate that other shortcuts were in error as well. No solution was found, but @pfrazee brought up the `localshortcut` module, and [electron/electron#15094](https://github.com/electron/electron/pull/15094).

**For Reference**: From the link in the previous comment, here are the issues I think could be related to this one:

- #1219 
- #855 
- #1100

**Comment by jbaicoianu** [comment]
I see the same behavior in Windows as well, it seems like a problem with how Beaker is handling keyboard focus - as if the event handlers are attached to some element, but that element loses focus when a tab is selected using this shortcut.  I can click anywhere within the app or within the tab's contents to refocus, and then the keyboard shortcut starts working again.

Interestingly, and perhaps a clue - if I have the URL bar focused, I get two presses out of this keyboard combination rather than just one before it stops working.  I wonder if there's an event handler in the URL bar's blur event which focuses the correct element?

**Comment by lvivier** [comment]
I believe this is due to a change in Electron in v3, the introduction of [OOPIF](https://www.chromium.org/developers/design-documents/oop-iframes) in Chromium. The relevant WebView documentation is [here](https://electronjs.org/docs/api/webview-tag#internal-implementation).

Electron issues:

- https://github.com/electron/electron/issues/14883
- https://github.com/electron/electron/issues/14258

I built master with `electron@3.0.0-beta.5` and I can confirm this bug doesn't manifest in that version.

One solution might be to forward keydown events from the webviews up to the BrowserWindow. @pfrazee can you give me a pointer about where to start playing with webview ipc? Would this belong in beaker/core (looking at [app/webview-preload.js](https://github.com/beakerbrowser/beaker/blob/master/app/webview-preload.js))?
