### ISSUE TITLE
Very slow, showing 0 peers and other bugs

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1308]
Fritter, that I've already downloaded before, shows as loaded but is blank:
![image](https://user-images.githubusercontent.com/6765277/50788736-641a7180-12a1-11e9-8d15-36cbf5612062.png)

And another bug: when adding to watchlist, it says it has been found, but when clicking it shows error again.

![image](https://user-images.githubusercontent.com/6765277/50788651-21f13000-12a1-11e9-8492-5223fce35ecf.png)

I thought all that would be because of my slow Internet connection, but ZeroNet works and on Dat even on 300+ KBps (that is a reasonable speed) it isn't loading:
![image](https://user-images.githubusercontent.com/6765277/50788849-b65b9280-12a1-11e9-8770-dd1b601b47f8.png)

**Comment by DaniellMesquita** [comment]
Probably my Beaker version is outdated, so I'll show its version: 0.8.1

**Comment by pfrazee** [comment]
There are times where dat fails for reasons other than the network. For instance, due to corruption, or because you cleared the internal dat cache and sometimes Beaker doesn't reinitialize the internal cache correctly. I'm going to close because we're aware of those, but feel free to reopen if you have more information about this particular issue.
