### ISSUE TITLE
Question: Any way to guarantee code delivery?

### ISSUE THREAD

**Issue by jcalfee** [beakerbrowser/beaker#1323]
Is it possible to change a sites' version history if it has only one seed?  In a way version 2 (for example) could change.  I'm thinking about a case where a 3rd party recommends a particular version and wants to secure with a known good hash.  Would be nice to provide that hash beaker to beaker (in ?version_hash=) to ensure that is in fact the same code.

**Comment by pfrazee** [comment]
We're working on adding a URL form that we call the "strong link" which will include a hash to enforce that. The format we're discussing is `dat://{key}+{version_num}+{hash}/`

**Comment by jcalfee** [comment]
I was thinking that the version could be optional, but I think that is a bad idea because that would make the url noncanonical.  I assume the version is in there just for the user's benefit?

Also good if the browser will fail check the version and hash and fail if they do not match.  You might report the correct version in the error if the key and hash match.

**Comment by pfrazee** [comment]
We currently support `dat://{key}+{version_num}/`, which provides a soft guarantee of a specific content because the protocol forces a linear history. The idea of the strong link is to add on the stronger guarantee. Plus, including the version will improve performance significantly.

> Also good if the browser will fail for the wrong {version_num} for the {hash} (forcing only 1 canonical url for that version of the code). You might report the correct version in the error if the {key} and {hash} match.

That's the idea. If the hash doesn't check out, it'd be similar to a bad SSL cert.

**Comment by jcalfee** [comment]
Things I would consider:
* `dat://[a-z0-9]` is alone and has its own local-storage (like it does now)
* If `{version_num}` and `{hash}` are provided require both to match
* If either `{hash}` or `{version_num}` are omitted tools should fill in the missing value and re-write or re-print the full URL with both.  The goal is to have only 1 other possible location for local-storage.  So any value URL should only resolve to either the **versioned local storage** or the **non-versioned local-storage**.
* Other tools like the `dat` command line should adopt the same behavior as much as possible
* For `{hash}` consider:
  * Since the `+` above is departing from the domain name standard, it may be reasonable to allow mix-case in the `{hash}` to save space.  That would allow for a URL safe format like base58 (unlike base64, contains only letters and numbers).
  * Identify with a prefix very short prefix like `H` for hash that will help users and support
  *  (ex: `HPH4nmLYxgWyq9FqpzvxAEPZ5ZdwGZjmvusLqPDCk7mu1`)
  * Consider sha2-256 as this is widely used.
  * [Multi-hash](https://github.com/tinybike/multi-hash#usage) ([spec](https://multiformats.io/multihash/#the-multihash-format)) provides a way to upgrade the hash-type in the future should something faster, smaller, or more secure become available in the future and allow upgrading without too much confusion.  Consider that an upgraded hash may lead to a 3rd possible local-storage location but tools may check for this.. (Ex `HQmPH4nmLYxgWyq9FqpzvxAEPZ5ZdwGZjmvusLqPDCk7mu1`)

**Comment by pfrazee** [comment]
I can't dig too much into this yet, but I wanted to point out a couple things:

1. The `+` correctly parses in existing URL handlers as part of the domain (including `window.URL`).

![screen shot 2019-01-25 at 11 33 30 am](https://user-images.githubusercontent.com/1270099/51762342-11a8c580-2095-11e9-9a27-2558c2565927.png)

2. Therefore we need to stay case-insensitive.
3. Eventually the versioning system will have tag labels which will probably replace the `{version_num}` so that it will be `{version_num|version_tag}`

**Comment by jcalfee** [comment]
Yea, no rush, I'm just thinking long term how this might be done.  Another idea, is that "Make a copy" does effectively the same thing as freezing to a version hash.  If you had a need to check a `{hash}`, the make a copy screen might be a place to display that.  I guess this would fragment seeders though.
