### ISSUE TITLE
Beaker froze again 

### ISSUE THREAD

**Issue by ookangzheng** [beakerbrowser/beaker#1358]
Operation System: Mac OSX 10.14.3
Beaker version:v0.8.6
 
Freeze while open 3 tabs

**Comment by suttonwilliamd** [comment]
OS: Windows 10 Home
Beaker version: 0.8.6

It's not very clear what all is known about the recent freezings, so I hope more people weigh in here.

I tried making a New>Website from the hamburger menu and everything was going good. I set the name, turned on preview mode (the toggle), added a Readme and set the local dir in Settings. I came back to Files clicked on Preview and freeze.

Possibly not related, but I have to ctrl+alt+del > End task on all beakerbrowser instances before it will open again, so I did all that and opened again. Opened the library to open my site and preview it.  Preview consistently freezes at this point.

I repeated opening, trying to preview the same site and experiencing the freeze about 3 times to make sure I was right about it being consistent when I came here to write. I forgot to close all the instances though, and so now I've got a 205 MB "Beaker Browser.DMP".

Not sure how useful it is, and had no idea it would generate, but it did. Want it?

**Comment by pfrazee** [comment]
Hey, yeah I'm sorry about this. We've got an issue open at https://github.com/beakerbrowser/beaker/issues/1333 so I'm going to close this as a duplicate.

This issue is caused by a use-after-free in the Electron code which solved by https://github.com/electron/electron/pull/17267. @suttonwilliamd your description matches the issue; it's caused by the custom protocol code, so anything that touches a `beaker://` or `dat://` page. As soon as that PR gets merged and released, I'll put out a new version of Beaker.

So sorry about this issue.

**Comment by tiotrom** [comment]
I can confirm on Manjaro Gnome it freezes many times for so many reasons. Like clicking the network debugger. Hope it will get fixed soon. Cheers!

**Comment by pfrazee** [comment]
@tiotrom Yeah it freezes, like, all the time. It's unusable. I'm just held up by Electron's release process to get the fix out.
