### ISSUE TITLE
Cannot close it

### ISSUE THREAD

**Issue by tiotrom** [beakerbrowser/beaker#1359]
Operation System: Manjaro Linux, Windows 10
Beaker version: Beaker 0.8.6

Closing Beaker does not really close it. I have to murder it from the task manager or system monitor in Linux. Else I cannot re-open it.

**Comment by Butterfly** [comment]
Hi.. Just a regular nosey person here who has come to ask...

That's interesting that it's both Linux and Windows. My nosey question is.. what's your memory like in your setup? That would mean both your physical memory and whatever swap setup you might have set up.

I've just recently had a little 4-watt light bulb go off overhead regarding what we're experiencing versus how things are swapping around as we compute. I'm on Debian and use `free -m` to see what's going on with mine. When my various programs do exactly what you're describing, repeatedly running `free -m` has helped me visualize how the memory flops back and forth *all over the place* as things shut down.

This is mine right now on a little ASUS EEEPC:

```
$ free -m
                  total        used        free      shared  buff/cache   available
Mem:            979         712          75          48         191          76
Swap:          2999        1501        1498
```

There's such a thing as having too Swap for the physical memory we add, but I'm not sure what that is because Users have all kinds of opinions about it. :smile: 

By continuously hitting that `free -m`, I've finally seen the light as to how it might cause problems.  It might kind of be like the computer gets lazy and throws as much as it can into Swap... and then, depending on how we each set things up, maybe there's no place for it to come back out **in a timely manner** so that the program can do what it needs to do to shut down **in a timely manner**....

DISCLAIMER :: That doesn't mean that this is what *you* are experiencing. I just decided to toss it out there because it *is* what I'm experiencing with mine when *I* have to kill *my* packages multiple, multiple times a day. :smile:

**Comment by pfrazee** [comment]
@tiotrom Thanks for filing. I'll try to reproduce on Windows or Ubuntu. I haven't experienced it yet.

**Comment by tiotrom** [comment]
Here's a Linux demo or the issue https://www.youtube.com/watch?v=jmNj5jS1aog&feature=youtu.be

**Comment by pfrazee** [comment]
Okay interesting, thanks

**Comment by pfrazee** [comment]
I was able to reproduce and fix it in Windows. Let me know if you still experience the issue. Thanks again for filing.

**Comment by tiotrom** [comment]
@pfrazee great! I suppose it will be fixed on Linux too?

**Comment by pfrazee** [comment]
@tiotrom I haven't tested yet, I'm being optimistic (maybe without good reason) and expecting they were the same issue. We can reopen if not.
