### ISSUE TITLE
Rasterization not hardware-accelerated in OSX

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#136]
![](https://usercontent.irccloud-cdn.com/file/HdpUcDE6/Screen%20Shot%202016-10-15%20at%2010.32.59%20AM.png)

May impact performance. Should see why, and try to re-enable the hardware accel.

**Comment by pfrazee** [comment]
I was able to enable hardware accel with `app.commandLine.appendSwitch('force-gpu-rasterization')` but I'm not sure that's a good idea. I'm not sure why it was disabled, and, on my device, it's disabled in both Chrome and Electron.

**Comment by pmario** [comment]
It's probably due to security concerns: 

see: https://cialu.net/enable-hardware-acceleration-firefox-make-faster/ and
https://security.stackexchange.com/questions/13799/is-webgl-a-security-concern

The first link is FireFox related. But the issues seems to be WebGL related, which may affect every browser. ...

**Comment by pfrazee** [comment]
@pmario thanks for the heads up

**Comment by pfrazee** [comment]
Seems to be fixed upstream.

**Comment by pmario** [comment]
> Seems to be fixed upstream.

Any links?

**Comment by pfrazee** [comment]
No I just checked chrome://gpu on my beaker and it was working again.
