### ISSUE TITLE
Tabs sometimes are unable to close, javascript intinsive websites freeze.

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/beaker#1470]
Operating system: Linux Mint 19.1

This is:

- [ Sometimes the tab freezes and I'm unable to close it. Certain websites stop working completely, like Twitter for example. ] a bug
- [ ] Not sure what feedback to give, as my skill is only in html and css.

**Comment by LWFlouisa** [comment]
Also I'm not finding the Beaker browser forum.

**Comment by Butterfly** [comment]
Hope this works, GRIN. Am emailing back instead of writing via Github.
I experience that *exact* same tab thing with other browsers. Right
now it's epiphany-browser aka "Web", version 3.22.7 at this very
second (on a different laptop that's running recently outdated
Stretch, GACK).

Web's a different kind of browser than e.g. Firefox or Opera. It
brings in a couple of extra packages along with on Debian. It's the
only one I can buy groceries with right now because it's about 95%
successful in muddling through our currently script-heavy Internet...

Well, except for those frustrating moments where it stubbornly DEFIES
me wanting to close a tab. Web, at least, DOES eventually cave in if I
punch at it long enough. :smile:

*waving* at you all via Puppy Linux Wary5 just this second (also) :smile: x 2!

**Comment by LWFlouisa** [comment]
I wonder if it's causing the URL click issue as well?

For a rundown: I used to be able to simply type in a URL and go there, but now I have to click it twice to go anywhere if it's outside of DAT.
