### ISSUE TITLE
Get and merge data folders

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1472]
I have Beaker on Windows and Linux.
Where are located the data folder with created sites? Could I merge the data from both?

**Comment by DaniellMesquita** [comment]
@pfrazee

**Comment by interfect** [comment]
I want to do this as well. I have the Beaker data folder (`%appdata%/Beaker Browser`, `~/.config/Beaker Browser`) from an old, disused machine, and I want to import all the Dats and ownership keys from that machine onto another machine I'm using now, which already has its own Dats, bookmarks, etc.

**Comment by interfect** [comment]
This is related to #815, which suggests that `Dat/Archives/Meta` and `Profiles` have between them the Dat data and keys. Unfortunately, merging `Dat/Archives/Meta` doesn't seem to be enough to add the archives to my library or the list of "my" Dats that I can write to, so there must be some important information in the `Profiles` sqlite database, which can't be merged by a simple copy-paste.

**Comment by interfect** [comment]
It looks like to really merge things you would have to copy the entries from the `archives`, `archives_meta`, and possibly `workspaces` tables in the one database into the other database. The private keys must be in `Dat/Archives/Meta`, and not in the database, since I can't find them in there, but I don't think Beaker picks up that you have them without the Dat being in the database.

One thing that looks like it might be working is to copy over everything in `Dat/Archives/Meta` and then visit each Dat you are supposed to own. Find the Dat in the Library under Recent and open its Library page. Beaker seems to think the Dat is in the Trash since it doesn't know about it, and shows a red banner to that effect, so you can restore it from the Trash by clicking the button in the banner. This seems to get the Dat into a state where Beaker shows the editing controls, but I'm not sure if it is then safe to edit it.
