### ISSUE TITLE
Live reload ignoring custom .datignores?

### ISSUE THREAD

**Issue by guybedford** [beakerbrowser/beaker#1507]
Operation System: Windows

Beaker version: 0.8.8

I've been playing around with the local live reload dev workflows here... have a simple TypeScript build running from `src` to `lib`, where the `src` folder is included in `.datignore`.

Even though the contents of the `src` folder are not included in the archive, when using the live reload feature, I'm still seeing two refreshes - one for the src change and one for the lib change, when I just want one reload for the final JS file.

Note that ideally I wouldn't even have the `src` folder in `.datignore`, since I don't mind publishing it (view source and all), I just don't want it triggering live reloading. Perhaps `reloadIgnores` or similar in `dat.json` might even make sense?

I'm probably missing something obvious but couldn't see any mention of this issue or any watch ignore features in past issues or the docs, so any pointers would help, thanks!

**Comment by guybedford** [comment]
Ah, it seems node_modules etc are ignored too, so simply supporting `.datignore` for live reload seems like the fix.

I'd be glad to contribute if you could point me to the part of the code.

**Comment by pfrazee** [comment]
Hey @guybedford, so `.datignore` and foldersync are getting deprecated from Beaker in the next release. We decided that because we're adding a FUSE interface, it might be smart to drop the folder-sync tool to reduce redundant concepts.

The downside of this is that, as far as I know, FUSE can't filter out files using a mechanism like `.datignore` which is a problem for projects using git or node_modules or etc. I've been thinking the solution will be to write a CLI tool which speaks to the `hyperdrive-daemon` (added in the new release) which basically does Beaker's previous syncing logic. I know it's a little frustrating that we're removing a feature, but I figure doing the same behavior via the CLI will be a better fit for the kind of users who need this solution.

The CLI is on my TODOs unless somebody else hits it first. I figure this would be a straight-forward feature to include in that tool.
