### ISSUE TITLE
dat URL specification

### ISSUE THREAD

**Issue by guybedford** [beakerbrowser/beaker#152]
Was really amazing to discover this project today. I'm just trying to read up more on where the `dat://` URL scheme is defined, but am struggling to find any resources (it doesn't help that `dat` doesn't google well either), is this protocol something that you have specifically defined in this project here?

Specifically I wanted to query why the versioned URL form is `dat://{hash}/{path}{[@version]}` and not `dat://{hash}{[@version]}/{path}`. This adjustment would ensure relative URLs would work nicely when for example serving web resources from versioned archives.

**Comment by pfrazee** [comment]
Hey Guy. Sorry for the weak docs!

For what they're worth, the resources to check are
 - https://beakerbrowser.com/docs/ (Im sure you know this one)
 - http://docs.dat-data.com/
 - [hyperdrive spec](https://github.com/datproject/docs/blob/master/docs/hyperdrive_spec.md) (hyperdrive is the internal name for dat's protocol)

There's not a spec for the dat url yet, and that's a really good point. Your proposed form is also a little more clear.

I had chosen to put it at the end, just because it felt simple and intuitive, but the issue of relative paths would trump that. I'll pull in some folks for comments.

**Comment by joehand** [comment]
Having the version after the hash sense to me since the version refers to the archive (hash) not the file. I like it!

**Comment by millette** [comment]
For reference, versionned dats are now ```dat://{hash}{[+version]}/{path}```.

**Comment by pmario** [comment]
@guybedford 

I'm not sure. Is this discussion still open? ... V0.7.3 implements the versioned URL in the way the OP proposed.

**Comment by pfrazee** [comment]
@millette is correct, that's the current spec
