### ISSUE TITLE
Starting a profile fails with File Not Fonud Error

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1567]
**Describe the bug**
Onboarding wizard seems to fail File Not Found Error

**To Reproduce**
1. Install prerelease
2. Launch it
3. Fill out the profile
4. Click Next

<img width="712" alt="image" src="https://user-images.githubusercontent.com/21236/81980172-fa238200-95e2-11ea-9f05-8f098f88a021.png">

**Comment by Gozala** [comment]
Tried to look at the debugger to see what's going on, but don't seem to get much here's the actual stack

```
Error
    at Function.<anonymous> (<anonymous>:1790:27)
```

And here is a bit more useful one

```
Error
    at eval (eval at <anonymous> (beaker://setup/unknown source), <anonymous>:1:1)
    at <anonymous>
    at <anonymous>:1794:22
    at onCbReply (<anonymous>:1947:5)
    at EventEmitter.onIPCMessage (<anonymous>:1884:14)
    at EventEmitter.emit (events.js:146)
    at Object.onMessage (init.js:59)
```

**Comment by pfrazee** [comment]
We just ran into this with @paul90 in https://github.com/beakerbrowser/beaker/issues/1567. For him, it was because he ran an earlier version of this new release that appears to have stored a problematic address.

I could probably find a way to surgically fix this if you want. The other option is to nuke your beaker user-data dir. (The issue is the `profiles` table in the `Profiles` sqlite DB -- if I'm right, it'll have a `dat://` URL in it. The solution is to clear that table.)

**Comment by Gozala** [comment]
@pfrazee I think you meant to refer to a different issue as you linked back to this one. 

I did delete profiles, there was indeed one records with dat url. However now beaker seem to get stuck on 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/21236/82016999-00dbe480-9637-11ea-847b-169be1593963.png">

I don't see any errors anywhere so not sure what's going on. I'll try with new profile os well

**Comment by Gozala** [comment]
With new profile things seem to work 🎉
