### ISSUE TITLE
Peers joining unshared drive

### ISSUE THREAD

**Issue by bndw** [beakerbrowser/beaker#1598]
**Describe the bug**
I downloaded the v1.0 beta release of BeakerBrowser and created a Chat Room from the template. After the site was created, I watched many peers connect and disconnect from the chat. I never shared the hyper:// link. I was under the impression the public key urls were undiscoverable unless I shared them. I was able to reproduce this by creating a second chat room.

**To Reproduce**
1. Create a Chat Room from the template
2. Watch peers join and leave

**Expected behavior**
Peers would only join if I shared the hyper:// link

**Screenshots**
![image](https://user-images.githubusercontent.com/4248167/82102830-a2aa1280-96c5-11ea-87c0-29d53d14de0a.png)

**Desktop (please complete the following information):**
 - macOS 10.15.4
 - Beaker v1.0.0-prerelease.1

**Comment by pfrazee** [comment]
Thanks for reporting! @andrewosh looks like something is off here

**Comment by andrewosh** [comment]
Digging into it a bit, the peers joining/leaving don't necessarily have access to the chat room drive. 

The way our replication system currently works is that when you get a new connection from the swarm, it will attempt to replicate the chat room over that connection -- because the remote side of does not have access to the chat room's key, the connection will immediately close. Alas, those quick open/close events are still triggering the peersocket's join/leave.

I'll dig into that, but this output doesn't indicate that any of those peers actually have read access to the drive (or know its key).

**Comment by andrewosh** [comment]
@pfrazee  @bndw  Fixed in peersockets 0.3.3.

**Comment by bndw** [comment]
@andrewosh Thanks for the walk through, makes sense.
