### ISSUE TITLE
Watch folder support

### ISSUE THREAD

**Issue by azcn2503** [beakerbrowser/beaker#1600]
**Is your feature request related to a problem? Please describe.**
In previous releases of Beaker browser, it was possible to create a site from a local folder on my computer and for the browser to watch the folder for changes. It would be really nice if this feature was reintroduced so that when I build and export my local site (I am using Next.js) that the site updates automatically.

**Describe the solution you'd like**
Reintroduction of the watch folder for changes functionality.

**Describe alternatives you've considered**
I've considered recreating the site each time but that seems like a lot of manual effort and will cause the URL to change.

**Additional context**
Perhaps I am misunderstanding how the protocol is supposed to function and I should instead rely on a new Beaker API.

**Comment by pfrazee** [comment]
@azcn2503 I think this is a reasonable request. I'm currently leaning toward building a CLI toolset that could handle this.

**Comment by guybedford** [comment]
I'd still love to see this to be able to use Beaker as a replacement for a dev server in development workflows. If so, this would make it my primary development browser - since it saves having to run a local dev server.

Standalone tooling sounds like a great first step, but having this exposed through a UI directly in the browser with no console necessary would allow me to develop with JUST vscode and an editor, without maintaining a running CLI process as one has to for a dev server currently. Managing UI state around sync being off / on / out of sync sounds hard but doable to me... perhaps it can be considered as two separate features - CLI then an optional UI for it in the browser?

**Comment by pfrazee** [comment]
@guybedford yeah noted, I'm giving that serious consideration

**Comment by pfrazee** [comment]
Assigning to a milestone so I don't lose track of this but it probably won't ship with prerelease.3.

**Comment by pfrazee** [comment]
BTW I'm going to go ahead and get the folder-watching tool done in Beaker (no CLI). Stay tuned.

**Comment by pfrazee** [comment]
Okay this is _mostly_ done. The only thing left to do is an auto-sync mode.

**Comment by pfrazee** [comment]
We're in business!

![CleanShot 2020-06-04 at 10 16 32](https://user-images.githubusercontent.com/1270099/83775580-b9041800-a64c-11ea-8124-9a0282fa2be2.gif)

**Comment by azcn2503** [comment]
Thanks Paul, I have just pulled and built the latest source. This is indeed working! Great implementation.

**Comment by pfrazee** [comment]
@azcn2503 Appreciate it! I'm sure we'll have some rough edges to smooth over but this should be a good start
