### ISSUE TITLE
Right-click Save As option for downloading files from links

### ISSUE THREAD

**Issue by erangell** [beakerbrowser/beaker#1619]
If I want to download a file from a link in Beaker (ex: a PDF file), I need to open the link then save the file using the "File... Export Page As" menu option.  It would be nice to have the Save As or Export function on the context menu for the link.

Example: hyper://0179c63933ac650471d69d3ae70a1b1755407b70a8a7b98cd21f47b8e670bc9d/

**Comment by tiotrom** [comment]
I just wanted to request this feature. We share our custom Linux distribution via Beaker and there is no way for anyone to properly download our ISO. Also, what if you can download entire folders?

**Comment by pfrazee** [comment]
Sure thing

**Comment by Butterfly** [comment]
> Also, what if you can download entire folders?

Just thinking out loud here since you all already received an expressed :+1: ... Linux Debian package `konqueror` describes itself as an "advanced file manager, web browser and document viewer". I used it a LONG time ago, via Knoppix, I think.

That "advanced file manager" part is what comes to mind now. Maybe `konqueror` has somehow jump started the possible coding that might drive that feature. My apologies if some other browser actually already has that in place and is why you asked. :smile:
