### ISSUE TITLE
Shared drive does not update with new additions

### ISSUE THREAD

**Issue by tiotrom** [beakerbrowser/beaker#1641]
Maybe I am confused as to how the new Beaker works but from my previous use I would share a folder and then Beaker will keep an eye on that folder and whatever I would add there, Beaker will index. It was a dynamic folder sharing. Now it does not update/index the folders that I share via New Hyperdrive or New Drive From Folder. I also checked the structure of the folder and the merge/dif section and is nothing there. I can add stuff to this folder but Beaker does not index it.

Is Beaker working differently now?

**Comment by tiotrom** [comment]
I am using Linux + the appimage. Manjaro Gnome more specific.

**Comment by tiotrom** [comment]
I am reading through the documentation here https://docs.beakerbrowser.com/beginner/creating-new-hyperdrives and I feel like Beaker works differently now than it did before. We used it to share folders with our own media creations like videos and images, with our followers. It was an easy concept: share a folder publicly that anyone can access and host. And whenever there is a change to that folder locally, Beaker pushed the change to all peers. Simple. Fun :). Is Beaker different now?

**Comment by pfrazee** [comment]
Yeah this is actually a dup of https://github.com/beakerbrowser/beaker/issues/1600. Going to close this issue to keep the number of open issues down.

You're right, we did lose a good feature on this one. The reason is a long story but that doesn't matter: point is that we do want to get this feature back and we're just working on the right way to do it. Sorry for the temporary loss!

**Comment by tiotrom** [comment]
Awesome to hear that. I loved Beaker for that feature. Knowing that is getting back makes me soo happy!
