### ISSUE TITLE
beaker.hyperdrive not throwing errors in custom webterm commands

### ISSUE THREAD

**Issue by matthewauld** [beakerbrowser/beaker#1696]
**Describe the bug**

beaker.hyperdrive methods do not throw the expected errors (assuming it should throw the same errors as running the commands in the regular chromium console.
**To Reproduce**

1. Install and run the following "example" command [here](hyper://9a5fc9e85b831606e158045569dbe63fd46bc4938a11e29beeda08e8fb85ec65/)
Code below in case I am not online
```
export async function example (opts = {}, arg1, arg2) {
  this.out("start")
  try{
    let x = await beaker.hyperdrive.drive("AAAAA")
    console.log(await x.getInfo())
    this.out("this should not run")
    this.out(x)
  }catch(e){
    this.out("this should run")
  }
  this.out("end")
}
```
2. The output is 
```
start
this should not run
{"url":"hyper://aaaaa/","version":null}
end
```

**Expected behavior**
Output of
```
start
this should run
end
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version beaker: Version: 1.0.0-prerelease.3 
**Additional context**
I maybe have just completely misunderstood how webterm is supposed to work, and if I have, I am sorry!

**Comment by matthewauld** [comment]
Oh, Should also note - this but appeared in prerelease3, but was not present in prerelease2.

**Comment by pfrazee** [comment]
So what's happening here is that `"aaaaa"` is technically not an invalid hostname for a hyperdrive. It's an invalid key, sure, but not an invalid hostname, and eventually when domain names get involved that'll matter.

Then the other thing is, `getInfo()` doesn't currently throw on a failed read. It's kind of like "get the info we have." You know we have no info because `version`, came back falsey.

If `readFile()` or similar didn't fail, that would be more problematic. (I'm going to close optimistically but feel free to reopen)

**Comment by matthewauld** [comment]
Ah! Ok. That makes sense. ReadFile does throw that error. Thanks! Sorry to bother.

**Comment by pfrazee** [comment]
No worries at all! Reasonable assumption on your part
