### ISSUE TITLE
cannot start 

### ISSUE THREAD

**Issue by erkrujjawal786** [beakerbrowser/beaker#1825]
hello all, 
I have downloaded beaker browser latest dmg file from the website, now when i am trying to open its showing me 
Failed to connect to daemon, retrying [info]
{ "category": "hyper", "subcategory": "daemon", "message": "Failed to connect to daemon, retrying", "level": "info", "timestamp": "2020-10-04T15:23:46.174Z", "type": "data", "target": {} }

and its keep on coming , browser is not starting , i checked the version its Version 1.0.0-prerelease.7 (1.0.0-prerelease.7) , please let me know how to start the browser,

Thanks

**Comment by pfrazee** [comment]
Sorry for the delayed response, I declared inbox bankruptcy for a couple months while we finished 1.0.

I never figured out exactly what caused that with the old code, but we changed the "daemon" in the 1.0 and I haven't seen that since. I'm going to (hope) this is resolved and close optimistically, please let me know if it persists after 1.0 releases.
