### ISSUE TITLE
Chrome Sandbox is disabled in electron. Is this secure?

### ISSUE THREAD

**Issue by wanderer** [beakerbrowser/beaker#19]
The Chromium sandbox  was basically ripped out of electron. Is this a security concern to beaker?

Ref: http://blog.scottlogic.com/2016/03/09/As-It-Stands-Electron-Security.html

**Comment by pguth** [comment]
Nice article! There has been a [follow-up blogpost](http://blog.scottlogic.com/2016/06/01/An-update-on-Electron-Security.html) mentioning the now implemented fixes and also the official [security guide](http://electron.atom.io/docs/tutorial/security/).

**Comment by pfraze** [comment]
Thanks @wanderer for bringing this up, and thanks @pguth for the useful followups.

To recap: the Chromium sandbox is an extra layer of protection around the Web platform sandboxing. It protects from exploits against the Web platform's implementation. Electron doesn't have it enabled.

In my opinion, It is a security concern, but not a critical one. We should track its status, and possibly copy from Brave's solution when Beaker is more mature.

**Comment by pguth** [comment]
I would rather rephrase to: It is a critical security concern but we can ***carefully*** manage for the time of initial development because:

a) it seems the development is going quickly.
b) the brave browser pioneered a solution.

In the words of the [electron security guide](http://electron.atom.io/docs/tutorial/security/):

> [...] be aware that displaying arbitrary content from untrusted sources poses a severe security risk that Electron is not intended to handle. [...] if your application executes code from an online source, it is your responsibility to ensure that the code is not malicious.

It closes with:

> If your goal is to display a website, a browser will be a more secure option.

**Comment by pfraze** [comment]
@pguth Calling this critical obscures the nature of the issue. It makes it sound like there's a known vector to escape the Web API sandbox. That's not the case. The issue is, if there is a vulnerability in the Web API or plugin system, there's no process-level sandbox to contain that failure.

Otherwise, we're in agreement. We're on a tight-rope without a net. Before Beaker can be considered a mature browser, it'll need to adopt a process-level sandbox.

**Comment by pguth** [comment]
> Calling this critical obscures the nature of the issue. Calling it critical makes it sound like there's a known vector to escape the Web API sandbox.

Ah, I see.

**Comment by pfrazee** [comment]
Important progress made by electron recently: https://github.com/electron/electron/pull/6919

There may still need to be more work before I can adopt that flag here. Tracking issue: https://github.com/electron/electron/issues/6712

**Comment by pfrazee** [comment]
The process-level sandbox is now enabled
