### ISSUE TITLE
500 IPFS Daemon not found. Start the daemon and try again.

### ISSUE THREAD

**Issue by Miserlou** [beakerbrowser/beaker#211]
Operation System: OSX
Beaker Version: Latest Binary Download, 0.5.0

Regular web pages work just fine, but any IPFS message gives me this error. 

In /Users/MYNAME/Library/Application\ Support/Beaker\ Browser/, there is no IPFS folder. Manually creating this directory did not help.

Testing with this URL: fs:/ipfs/QmU1GSqu4w29Pt7EEM57Lhte8Lce6e7kuhRHo6rSNb2UaC

Related: https://github.com/beakerbrowser/beaker/issues/73

**Comment by jbenet** [comment]
It may be useful to use the https://github.com/ipfs/npm-go-ipfs-dep package to run an ipfs daemon from within beaker. ideally using different ports or `/0` so it doesnt clash with other things

**Comment by pfrazee** [comment]
I've currently got Beaker setup so that you have to run the IPFS daemon independently. @Miserlou do that for now. I'll try to get IPFS auto-installing in 0.5.1 this weekend.

**Comment by pfrazee** [comment]
You can install from https://ipfs.io/, then run `ipfs daemon` to start it.

**Comment by Miserlou** [comment]
Oh, okay, that worked!

But.. I installed Beaker so I wouldn't have to do that. :-P

**Comment by pfrazee** [comment]
Hah fair enough. It's kind of a tricky sitch, and @jbenet you may have a thought about this:

If you're an existing IPFS user, it's better to use the daemon you already have running, because then the dataset is shared, right? And if I use a different port & data-dir, then there may be two IPFS daemons running at once.

One option might be to build a better "No IPFS Daemon found" page, that can optionally run the daemon installation and setup for you.

**Comment by Miserlou** [comment]
It's pretty to poke the port to see if the demon is running, if not, load one up.

**Comment by pfrazee** [comment]
Yeah that's true

**Comment by jbenet** [comment]
cc @diasdavid @haadcode to provide help on this

**Comment by jbenet** [comment]
> If you're an existing IPFS user, it's better to use the daemon you already have running, because then the dataset is shared, right? And if I use a different port & data-dir, then there may be two IPFS daemons running at once.

Yes, this is indeed tricky. We're still figuring out the best way to have apps "use a local daemon if available" with proper permissions isolation. But for simplicity, for now best to assume each app is an independent daemon. They will still connect between them and move data quickly. though yes--definitely wonky as you'd like to share the object cache. (the network connections too maybe, but this is arguable)

> One option might be to build a better "No IPFS Daemon found" page, that can optionally run the daemon installation and setup for you.

We discourage this, because the goal is to have things always "just work" for people. Applications should just work out of the box -- similar to electron. You dont tell people to install electron manually, it ships a huge bundle every time with the `.app` package of an application, even if the same electron bundle exists in people's machines already. 

Maybe take a look at how Orbit does it. Note it provides a config so people can run multiple instances if they so desire. https://github.com/haadcode/orbit

**Comment by haadcode** [comment]
I'm using https://github.com/haadcode/ipfs-daemon#usage in Orbit to manage the daemon. 

There's an undocumented flag in the latest version of `ipfs-daemon` called `useRunningDaemon` where you can specify from which host:port to look for an existing daemon (eg. `useRunningDaemon: 'localhost:5001'`). If it's not provided, ipfs-daemon will spawn a new, isolated one (you can specify the path and addresses) for you. Run with `LOG=debug` to get more detailed logging info.

This works quite nicely for Orbit and abstracts away the problems / tricky bits there are to booting up a daemon, so it may work well for you too. 

Please note that the latest version of ipfs-daemon uses go-ipfs 0.4.5-pre1 which is basically the current master branch of go-ipfs.

**Comment by millette** [comment]
Note that IPFS is deprecated since 0.7, see #407.

Should this and other IPFS issues be closed, except maybe #480.

**Comment by pfrazee** [comment]
@millette yes it should, thanks
