### ISSUE TITLE
Feature: Scuttlebot API

### ISSUE THREAD

**Issue by marcelklehr** [beakerbrowser/beaker#231]
Hi,
I was wondering how much effort it would take to provide the scuttlebot client API to web applications?
This could be a stepping stone to providing full integration with scuttlebutt, allowing people to share apps in blobs on there that as well that could be used with beaker, and making decentralized web apps possible (afair, beaker supports only static dat sites atm?).
Let me know what you think! :)

**Comment by pfrazee** [comment]
Hey @marcelklehr. As a founding scuttler I'm a big fan of the tech, but I've decided to use only Dat in Beaker. 

Dat uses fundamentally similar concepts, including append-only logs to publish content, but then adds improvements such as compaction (keeps data from growing endlessly) and a global discovery-network for archives (more reliable downloading).

Since Dat is able to cover all of SSB's usecases, I think we're better off avoiding the extra overhead of another protocol.

**Comment by marcelklehr** [comment]
Thanks for the in-depth reply! Dat (and IPFS) to me seems to be centered around folder sharing. How would I implement, for example, a collaboration app, or a social network on top of dat?

**Comment by pfrazee** [comment]
I wrote about that here: http://pfrazee.github.io/blog/achieving-scale

You can use the pure P2P architecture I described, or use the crawler hybrid as well.

**Comment by marcelklehr** [comment]
That was illuminating. Is it possible to create dat sites with a different materialized view than a folder, though? When using CRDTs that would avoid the hassle of re-implementing gossipping on top of a gossipped data structure. It's probably doable as is, but I'm not sure it's the best aproach.

**Comment by pfrazee** [comment]
Sure.

If you want to treat a Dat like a log, you can have a folder where every entry is (eg) a .json named with a timestamp. You just keep appending files.

You'll process your "log", or any other set of files, by reading them into memory and then merging their data, same as with SSB.

You can store the materialized views in localStorage or indexdb, or in a dat.

Three things are missing in Dat, that will help you in the future. They're just todo items:

 1. We don't yet track the timestamp of when a file was *received.* Receive-time is handy for correcting against bad author timestamps. Eg, if the author's timestamp is > than your receive timestamp, you can use the receive-time instead.
 2. We don't yet expose cryptographic identifiers on each file. For example, in SSB we had a SHA id for every message, which was very useful because it wasn't forgeable. That's especially handy for CRDTs, because a SHA guarantees a happens-before relationship: if you have the SHA, then the data you're referencing was definitely created in the past.
 3. (Im not sure but) I dont think we guarantee that creation-times are immutable yet. Just a heads up there.

I should probably open issues for all 3 of those items...

**Comment by marcelklehr** [comment]
Thanks for the explanation! I look forward to creating my first beaker app :)
