### ISSUE TITLE
dat API: Allow forking dats

### ISSUE THREAD

**Issue by marcelklehr** [beakerbrowser/beaker#258]
This would be a nice addition to the dat web API, in my opinion.

**Comment by pfrazee** [comment]
Oh yeah, definitely. Maybe this signature:

```js
dat.forkSite(url, { title, desc })
```

Where `url` is the target site to fork, and `title` and `desc` are optional overrides.

We also need to consider whether there should be tools to check on the download-state for a site, and to trigger full download. Because, if you fork a partially-downloaded site, you won't get all of the files.

**Comment by marcelklehr** [comment]
+1 on the API.

For partially-downloaded sites, I feel like forkSite should be transactional, so that when I request forking a site, I'd need to wait until it's fully downloaded for the forking action to complete. I can't think of a case where I could use a half-complete fork?

**Comment by pfrazee** [comment]
Yeah, partial forks would probably not be the common case.

However the download might take a long time if it's a big site. We might
need download monitoring APIs too, so apps can explain what's up with the
wait. Eg, a download event, and a method to get current progress %

**Comment by pfrazee** [comment]
Consolidating this issue into https://github.com/beakerbrowser/beaker/issues/311, closing
