### ISSUE TITLE
wrong tooltip - tab close button

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#270]
Operation System: ubuntu 16.10
Beaker Version: 0.6.0 master:latest

IMO an image is worth more than 1000 words :) The "new tab" tooltip is still active when close element is already selected. 

![beaker-issueg](https://cloud.githubusercontent.com/assets/374655/22203279/a4699508-e16c-11e6-9cb5-95ca21333cf6.gif)

**Comment by pmario** [comment]
I'll probably be able to fix it. ... There's also a problem with the element color and the the position of the X. Should I create a PR?

**Comment by pmario** [comment]
Is this also a problem with other OSes?

**Comment by pfrazee** [comment]
> The "new tab" tooltip is still active when close element is already selected.

Yeah that's easy to fix: just need to put a `title` tag on the x button.

> Is this also a problem with other OSes? Or just for me?

It doesn't happen in OSX. I've been planning to redo the tabs with SVGs, to deal with the aliasing on those edges. Let's not worry about the x for now, since I can probably do that in SVG too and get better cross-platform results.
