### ISSUE TITLE
Opening a new tab should not bring that tab into focus

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#291]

**Comment by pfrazee** [comment]
There's actually an issue in Electron 1.5.0 or 1.6.0 (I forget which starts
it) that makes this complicated, but -- I think -- still doable.

Basically, if a webview is created as 'hidden', it will never render. It
has to be visible first, and then can be hidden (almost immediately). If
it's display: none, it won't ever start loading.

There are three solutions I know:

 1. Set width & height to 0 to hide a webview. This is Electron's
recommended solution. The problem is, the page has to reflow when shown.
Not a good experience but not the *total* worst.
 2. Use translateX(-100%) to push the webview out of view. Works ok, except
that whenever your resize the window, all webviews do reflows at the same
time because they're all actually active, meaning resize performance is
awful.
 3. Always focus new tabs so that they get a chance to render. Then we can
hide all we like!

I think probably a better solution will be, if we need to open a new tab
without focusing it, to open it using solution 1 or 2, and then hide with
visibility after a few ms pass.

**Comment by pfrazee** [comment]
Solved with a bit of hackery in v0.7
