### ISSUE TITLE
Rendering errors in the tabs region on Ubuntu

### ISSUE THREAD

**Issue by ThatOneGamer999** [beakerbrowser/beaker#326]
Operation System: Ubuntu 16.04 LTS
Beaker Version:0.7
Found a small glitch in the UI involving icons staying put on closing a tab:
![image](https://cloud.githubusercontent.com/assets/17152768/23571858/dda74f24-0041-11e7-9d8b-f32ed20d56e2.png)
Can attach the build binary if needed.

**Comment by pfrazee** [comment]
I dont see a glitch -- are you referring to the 4 icons in the page?

**Comment by ThatOneGamer999** [comment]
Whoops, wrong screenshot. It seems that when selecting the window, it resets.
I'm cropping a screenshot right now, hangon

**Comment by ThatOneGamer999** [comment]
![cut-screenshot01](https://cloud.githubusercontent.com/assets/17152768/23580843/a2ebf8fa-00df-11e7-868e-b4fedf73eaa6.png)
There, notice how the new tab icon is duplicated?

**Comment by pfrazee** [comment]
Oh yeah. I'd bet money that's because we don't have a background color set and transparency isn't supported, therefore what you're seeing is a region of visual memory that isn't being overwritten by subsequent paints. Until we prettify non-OSX (#328) we can solve this by setting a background to the tabs region.

**Comment by pfrazee** [comment]
Solved in the v0.7 branch
