### ISSUE TITLE
Feature Request: Markdown with Interpolated Variables

### ISSUE THREAD

**Issue by DaveJarvis** [beakerbrowser/beaker#350]
Consider the following files:

**$HOME/htdocs/path/index.md**

    ${application.title} is FOSS. [Download](${application.url}) version ${application.version}.

    Contact [${application.author.email}](${application.author.name}) for details.

**$HOME/htdocs/def/variables.yaml**

    application:
      title: Beaker
      version:
        major: 1
        minor: 2
        full: ${application.version.major}.${application.version.minor}
      url: http://cdn.host.com/program/${application.version.full}/filename.zip
      author:
        name: Author
        email: paul@gmail.com

**$HOME/htdocs/path/variables.conf**

    index.md=/def/variables.yaml

**How it Works**

1. User visits **http://host.com/path/index.md**.
1. Browser requests **http://host.com/path/index.md**.
1. Browser requests and caches **http://host.com/path/variables.conf** (like a default icon).
1. Browser looks up **index.md** within **variables.conf**.
1. Browser requests **http://host.com/def/variables.yaml**, as per the mapped definition.
1. Browser interpolates and substitutes values from **/def/variables.yaml** into **index.md**.
1. User sees stylized **index.md** with variable values injected.

**Notes**

* Substitution could use the Aho-Corasick algorithm for multiple replacements within the text.
* Interpolation would need to catch infinite recursion.
* Non-existent variables would render as their variable key name and stylized.

While **index.md** could be generated server-side, having this behaviour part of a browser would lower the technological barriers to adoption, proliferation, and education of Markdown with variables due to being simple static file requests.

**Comment by webdesserts** [comment]
Third Party Opinion: I think it would be in Beaker's best interests to avoid custom functionality like this in markdown for two reasons:

1. I think one of the benefits of Beaker is that for the first time in a long time, the web will have a low barrier to entry (think of people who's only interaction with html was MySpace or similar). This means that many peoples first and only interaction with Markdown would be with Beaker. I think having custom functionality like this on top of Markdown would cause newer users to assume that Beaker Markdown **was** Markdown in a similar fashion that many people tried to use features like ascii tables in parsers outside of Github Markdown before CommonMark attempted to standardize those features. I think that markdown rendering in beaker benefits newer users the most who are already going to be busy enough learning what css js and html are. Adding variable interpolation and yaml files will imo _increase_ the barrier to entry rather than decrease it.
2. With Beaker it is now not only possible to publish your `build` files, but to also publish your entire build process as well. Meaning that the barrier to entry for accessing these types of extra features is already _really_ low for the more experienced devs as it's just a fork away. 

In general, I'm not completely opossed to these types of features, but it might be good to walk softly and let the community experiment a little bit first. At the very least, you would probably want to get opinions from the CommonMark team, before including these types of language extensions.

**Comment by DaveJarvis** [comment]
> Adding variable interpolation and yaml files into the mix will imo increase the barrier to entry rather than decrease it.

That's fallacious. A product feature needn't raise any bars. A person can learn basic HTML without learning CSS, foregoing the benefits of CSS. Documentation can be split into basic and advanced usage (i.e, "further reading"). In other words, just because a feature exists, doesn't mean it needs to shine in a spotlight or in any way detract from simpler usage.

> At the very least, you would probably want to get opinions from the CommonMark team, before including these types of language extensions.

That's a sound proposition.
