### ISSUE TITLE
Configurable fallback (404) page on Dat sites

### ISSUE THREAD

**Issue by millette** [beakerbrowser/beaker#561]
Right now, we can write SPA website but have to use # in the URL, like /#page1, /#page2 so a visitor will get content from / and JS takes care of handling the routing with #. Otherwise, /page1 and /page2 don't exist.

With a bit of "server side" code, we could redirect all traffic to / to have prettier urls, and let JS handle routing.

(Sorry if I'm making it very confusing...)

**Comment by pfrazee** [comment]
Two possible solutions:

 1. We wait for service-workers to land, which could handle this programmably
 2. We add an attribute to the dat.json manifest which provides a "fallback response" for 404ed page requests

I think I like 2 because, providing a 404 page is a natural requirement, and having to use a service-worker to accomplish something like this is a real PITA.

**Comment by millette** [comment]
I'd go for 2 as well. Not sure if dat.json is the right place, since as an owner, I don't have much control over that file (it's all handled by beaker).

So, either more control on dat.json, or another file (manifest.json or something).

**Comment by pfrazee** [comment]
We're thinking about restoring more direct control to dat.json, as the tooling has improved

**Comment by webdesserts** [comment]
I would also like to see something along the lines of option 2. Will be easily accessible for the more basic sites where someone just wants a pretty 404 page, but would also enable single page applications. I think it would pair well with Beaker's ability to rapidly get sites up and running.

**Comment by pfrazee** [comment]
I'm sold on option 2. Let's add a fallback resource attribute to dat.json.
