### ISSUE TITLE
Request: add custom-domain-names

### ISSUE THREAD

**Issue by anefzaoui** [beakerbrowser/beaker#631]
This more of a feature request, where as the Beaker community grows larger, a better solution to make "relevant" and "popular" beaker websites known and easily accessible is to add the ability to choose a domain name sort of like the nickname logic in websites where the first to get the nickname is the one who exclusively owns it, until a month after the user deletes their profile, whereas it would be in Beaker until a month after the creator un-publishes their website.

WDYT?

**Comment by pfrazee** [comment]
Would this differ from DNS? We do support DNS with dat.

**Comment by Plasmmer** [comment]
.bit and .eth address can be a thing.

**Comment by anefzaoui** [comment]
> Would this differ from DNS? We do support DNS with dat.

Nah I'm talking about words just like actual domain names in the centralized web, say I want to publish my website under the `dat://ahmed.nefzaoui` or `dat://ahmednefzaoui.bkr` and such examples :)

Eventually there will be websites with mass numbers of peers and I think it would be cool if users can easily remember how to access them and such.

**Comment by pfrazee** [comment]
@Plasmmer .bit and .eth are cool tech but not right for Beaker. We feel very strongly that Proof-of-Work consensus is too inefficient to become part of the Web platform. (see https://beakerbrowser.com/docs/inside-beaker/other-technologies.html#why-not-a-blockchain)

@anefzaoui we strongly considered that with something called [the app scheme](https://github.com/beakerbrowser/beaker/wiki/App-Scheme). The problem is that it would cause a lot of 404s. URLs have to be universally shareable. If a nickname isnt global, then people  would copy-paste the nickname URLs and expect them to work.

Instead, we might be able to do some interesting UI things in the URL bar. For instance, with [Installable Web Apps](https://github.com/beakerbrowser/beaker/wiki/Installable-Web-Applications), we might be able to put a nice name in the rendering of the URL for installed apps/sites, so that it looks like...

```
dat:// [Ahmed's Website] /blog.html
```

And then when you click the URL bar, it reverts back to the full raw URL (for copy pasta).

**Comment by anefzaoui** [comment]
Humm, sad. I'm not sure I understand what exactly do you mean with nickname being or not being global. But I looked at it from a slightly technical point view where both full raw URL or unique nickname URL are strings made up from characters that can be picked by a logic in the browser..

**Comment by pfrazee** [comment]
Sorry, it's just not feasible to have shortnames without a registry system. You can use DNS by following this wiki: https://github.com/beakerbrowser/beaker/wiki/Authenticated-Dat-URLs-and-HTTPS-to-Dat-Discovery#proposal

**Comment by specious** [comment]
Looks like [datprotocol/dat-dns](https://github.com/datprotocol/dat-dns) is the module that queries `https://<domain>/.well-known/dat` on the HTTPS host to establish a dat:// address to a peer-to-peer version of a site requested as `dat://<domain>`.

Took me some research to figure all of this out.

**Comment by pfrazee** [comment]
@specious sorry that was a pain. Our documentation is still too scattered.

**Comment by specious** [comment]
I'm poking around.  Looks like `.well-known/dat` hasn't yet been officially [accepted](https://tools.ietf.org/html/rfc5785#section-5.1) into the [well-known URI registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xml).

**Comment by pfrazee** [comment]
Yeah we haven't submitted it yet.

**Comment by specious** [comment]
It might become standard *de facto* 👍
