### ISSUE TITLE
Add a proxy configuration to the dat protocol

### ISSUE THREAD

**Issue by felix91gr** [beakerbrowser/beaker#682]
Operation System: Linux
Beaker Version: 0.7.5

Hi all,

In the CS faculty, we want to use Beaker from campus. But outside of wired LAN, the uni’s network seems to be blocking some of the ports used by Beaker.

We can ask the IT department to open the ports, but they are usually closed to faculties’ requests. Therefore, we’re thinking of using a proxy: wired and therefore free of blockage, through which we would connect to the p2p network. 

We have permission to do so. Is it possible?

Thanks,
Félix

**Comment by pfrazee** [comment]
We haven't tackled this yet, and I haven't researched what it will involve, but I think it'd be a good idea. I'm going to turn this into a todo. I'll try to updated it with some research soon.

**Comment by joehand** [comment]
👍 been thinking about how to do this on a per-archive basis. (basically listen to incoming requests and download those files before responding)

Would be interesting to add a layer on top that would do a similar thing when requesting archives that don't exist yet in the proxy.

**Comment by ScriptTiger** [comment]
I think @joehand is basically describing a type of caching proxy setup, but I think there should be options for both caching and non-caching to work with different setups. Perhaps it could even work similar to other current Dark Web implementations where a simple service runs in the background to provide a SOCKS5 or HTTP/HTTPS proxy, and then they can in turn be easily chained into something like a Privoxy/Squid setup.

**Comment by xek** [comment]
I have the same issue as the original reporter - basically I can't try out Beaker on a corporate laptop and can't really recommend it to anyone else, or show it to them, because it doesn't work here. The only way out to connect to the wider Internet is through a proxy, so the best solution would be to make it autodetect proxy settings or, at the very least, have the option to provide this configuration manually.

I suspect there will still be connection issues, even after this specific issue is resolved. This is because Beaker wouldn't be able to accept connections behind a proxy by listening on a socket. The socks protocol has an option to bind ports, but I don't think it is widely supported. So, in that scenario, a different and more proactive connection strategy may have to be adopted.

**Comment by ScriptTiger** [comment]
Tor is open source and has plenty of methods around situations like that which maybe could be borrowed, all of their pluggable transports or forcing data over common ports like HTTP/80, etc.. In the meantime there's also just simple ssh reverse port forwarding, but I don't know the specifics of how the P2P pieces listen for the Beaker Browser or how many ports are needed, if they are known ports, etc. You could also try VPN software, depending on what exactly you're trying to do.

**Comment by xek** [comment]
I did a little research. So, apart from being more proactive in initializing new connections to Dat peers, this would require implementing a DHT proxy over the established TCP/IP connection. This is because the BitTorrent Kademlia DHT, which is used by Dat, only works on UDP.

@miguelfreitas implemented something like this in Twister https://github.com/miguelfreitas/twister-core/commit/e52f2c25275119bf43054cdf711b91fe16db3238

He wrote a blog entry about it: http://twister.net.co/?p=363

@pfrazee I'm curious how straightforward it would be to extend the Dat protocol that way. I see there is an extensions string in the first handshake, but I didn't find examples on how to use it.

Implementing something like BitTorrent peer exchange (PEX) will also be beneficial.

**Comment by leethax666** [comment]
I'm pretty sure I2P has a UDP transport and they are more open to p2p networks in general

**Comment by pfrazee** [comment]
BTW I'm not ignoring this issue, just don't have good responses yet. We're starting to think about how we want the next iteration of discovery to work. This thread will be helpful when we get into it.

If anybody's interested, we've established a proposals process called DEPs for speccing and modifying the Dat protocol, so that might be a good place to discuss this https://github.com/datprotocol/DEPs
