### ISSUE TITLE
Window menu should hide by default on Linux

### ISSUE THREAD

**Issue by handicraftsman** [beakerbrowser/beaker#700]
Operation System: Manjaro GNU/Linux
Beaker Version: 0.7.5
[No, really](https://media.discordapp.net/attachments/351625473069023232/368858066428624906/unknown.png)

**Comment by taravancil** [comment]
Can you please describe the issue you’re encountering? We don’t use that
Linux distro so we’ll need help diagnosing it.

**Comment by jpyper** [comment]
I'm not a project dev or anything. Just a enthusiastic user passing through. The only issue that I see with the image is possibly the New Tab before the Welcome to Beaker tab, which in most other browsers is the other way around. Other than that, I don't see a problem just from the image alone.

I have been building Beaker on both Debian unstable and Ubuntu 16.04 whenever there's a significant update pushed to the master branch.

After going back and looking for anything I might've missed, I think I spotted the actual issue. There seems to be a GTK3 bar across the top of the application and a Global Menu bar (Unity or GNOME3) at the very top of the screen showing where all the title bar stuff should be, thus the GTK3 bar at the top of the application is wasting screen space.

Just my 2 pesos.

**Comment by handicraftsman** [comment]
@jpyper correct. I say that just because some other electron-powered apps do not have this problem. For example: https://github.com/edipox/wunderlistux. It does not support GTK's app menu, but it does not have that nasty undisablable menu bar on linux. It even decorates the window manually!

**Comment by akoenig** [comment]
Those are the slightly nuances which are bothering me a lot. People spending their spare time into building awesome **OSS** products whereas other people yelling with deconstructive issue title like "Are you kidding me?". From my point of view this one root cause why people invested in OSS are burning out. Not understandable ...

**Comment by jpyper** [comment]
@handicraftsman While you did attach a screenshot in your OP, you didn't leave any details to _WHAT_ the actual problem was. I was just picking things out from your image that caught my eye to try to decipher what your issue might have been about. Developers don't have the time to try to guess what you are thinking. That's why it's always best to include specific details about the issue you are reporting.

This is a good page, that even I quite often reference to, for writing good bug reports:
[https://capgemini.github.io/testing/effective-bug-reports/](url)

The quoted paragraph below can be found about half way down the page at the URL I just mentioned above:
"**A picture is worth a thousand words, but only if it has words to go with it**

Bug reports should (almost) always have a screenshot. But they should (almost) never just be a screenshot. With just a screenshot, it isn’t necessarily obvious where the problem is. If it was that obvious, the developer probably would have spotted it before saying that the component was ready for testing."

**Comment by pfrazee** [comment]
Ok I'm going to say the issue here is that the window menu should auto hide in Linux.

**Comment by pfrazee** [comment]
Done
