### ISSUE TITLE
Reproducable crash with an empty tiddlywiki file

### ISSUE THREAD

**Issue by merlinuwe** [beakerbrowser/beaker#734]
Operation System: Latest Windows 10
Beaker Version: Version: 0.7.7 Electron: 1.7.4 - Chromium: 58.0.3029.110 - Node: 7.9.0

Hi, 

I cannot install an empty tiddlywiki file, downloades from here http://tiddlywiki.com/

Beakerbrowser crashes reproducable with the message "Beaker browser funktioniert nicht mehr". What can I do? (Later, I want to use my own tiddlywiki files.)

Greetings,

merlinuwe

**Comment by pfrazee** [comment]
There's a pretty good chance this is due to a crash bug in electron, which is a known issue. https://github.com/beakerbrowser/beaker/issues/474. We've merged a fix into Electron, and we're waiting for them to release a new version with the fix in it.

I'm going to close as a duplicate. If you could, watch #474 and when we have a release that fixes it, try your empty tiddly again. Thanks!
