### ISSUE TITLE
Feature request: Restore tabs from last time

### ISSUE THREAD

**Issue by cinnamon-bun** [beakerbrowser/beaker#737]
Operation System: OSX 10.11.6
Beaker Version: 0.7.8

Wishing for a setting to bring back the tabs from the last session when the browser is restarted.

I'm one of those users who keeps twenty tabs open to read later.  Losing my tab state is a major usability issue.

This would also make crashes less painful.

**Comment by pfrazee** [comment]
Seems like this would be a good default behavior for crashes. If anybody wants to hit this, here's what I'd suggest:

 - [ ] Save all tab state every time there's a change to it. (Possibly refer to how pinned tabs are saved)
 - [ ] Watch for orderly closes of a window, which suggests it's not a crash. Delete any saved tab state that's not pinned.
 - [ ] Restore all saved tab state on window open.

Something to note: we do have pinned tabs now, which is how you can save state on a per-tab bases.

> This would also make crashes less painful.

:( Yeah sorry about that. We've got a fix landed in electron, so that should stop in a coming release

**Comment by webdesserts** [comment]
@pfrazee seems that other than tab "what tabs are open" you'll also need to keep track of "what windows are open". We _could_ temporarily restore all tabs to a single window just to get the feature out there. Not sure how difficult tracking windows would be (I know some browsers try to track which monitor or workspace the windows were open on and how they were positioned on the screen).

Where would be a good starting point in the codebase to start looking into this change?

**Comment by pfrazee** [comment]
If you're going to save the window state as well (including even window positions) then you probably want to use [background-process/ui/windows](https://github.com/beakerbrowser/beaker/blob/beaker-0.8/app/background-process/ui/windows.js). I'd monitor any state-change events and write them to a json file in the user data, and then read from that .json if appropriate during startup.

For the tabs, I think you'll need to setup messages between the shell-window and the background-process for tracking the open tabs, which can then be stored to the .json as well.

**Comment by webdesserts** [comment]
Got the first bit working: **Multiple window restoration**

![multiwindowrestoration](https://user-images.githubusercontent.com/916253/35078032-cc8b54c6-fbc5-11e7-922d-f6ddd189c8de.gif)

**Comment by pfrazee** [comment]
Great!
