### ISSUE TITLE
Writing to dat.json with the Web API

### ISSUE THREAD

**Issue by jondashkyle** [beakerbrowser/beaker#850]
When attempting to write to `dat.json` with the Web API a permissions error is thrown, clearly for security reasons. My application exposes a settings interface—two of the fields are for Title and Description. It feels redundant to store this data elsewhere, and creates confusion when the Title has been updated in the application, but is not reflected elsewhere within Beaker.

Perhaps there could be a way of either white-listing keys which are writable in `dat.json`, or simply deleting keys which should not be writable (such as `url`.)

**Comment by pfrazee** [comment]
We have a new API in 0.8. `archive.configure()` which is designed to give write-access to the dat.json. I figured that'd be a good approach because it does what you're suggesting (ensures the integrity of the file) without adding custom semantics based on paths.

I need to improve its whitelist but it can do title and description right now.

**Comment by jondashkyle** [comment]
Beautiful 🎉

**Comment by pfrazee** [comment]
Ok expanded the number of fields you can configure() now too

**Comment by RangerMauve** [comment]
Is there a reference somewhere for all the new APIs in 0.8 that aren't out in the docs yet?

**Comment by pfrazee** [comment]
@RangerMauve I threw one together for you: https://gist.github.com/pfrazee/7dbfe58cc571cef3bc167f8b3c35c0ac

**Comment by RangerMauve** [comment]
Oh snap. I'm really liking these changes! It's gonna make DatArchiveWeb easier to finish, too. :D
