### ISSUE TITLE
Unhandled "File not found" after deleting dat.json

### ISSUE THREAD

**Issue by maxhallinan** [beakerbrowser/beaker#859]
Operation System: Ubuntu 16.04.3 LTS, macOS 10.13:
Beaker Version: latest on master

Problem: The web root of a site is often a build artifact, e.g. Jekyll's `_site` directory. In the case of Jekyll, rebuilding the site deletes most files (I think everything except hidden files). Many projects treat the dist directory as ephemeral. Beaker places the `dat.json` manifest in a site's  web root. If the web root is cleaned out when the site is rebuilt, `dat.json` is deleted. After `dat.json` is deleted, the user cannot read or update the archive title and description in the Beaker library. The only option is to recreate `dat.json` manually.

Steps to reproduce:
- Create a new site
  - Click hamburger icon to the right of the address bar
  - Click "New site"
  - Complete form
- Delete `dat.json` from site directory.
- Attempt to update site settings
  - Click hamburger icon to the right of the address bar
  - Click "Library"
  - Click site title in left sidebar
  - Click "Settings" tab
  - Update archive title or description
  - Click "Apply changes"
- Unhandled Promise error: `NotFoundError: File not found at HTMLButtonElement.onSaveSettings (beaker://library/main.js:1517…`

I'd like to submit a fix for this but I want to get feedback about solutions first. The error originates in these [calls](https://github.com/beakerbrowser/beaker/blob/master/app/background-process/web-apis/archives.js#L74-L75) to `updateManifest`. One option is to recreate the default manifest if the file is not found. This is either an addition to the `beaker.archives.update` method or to the pauls-dat-api `updateManifest` method. Not sure if this should be the default behavior of the library itself. The other option would be to exclude `dat.json` from the general archive updates. It seems like Beaker holds those updates in a staging archive until the user reviews and commits the changes. If that's true (I haven't looked into it deeply), then a deletion of `dat.json` could just be ignored unless the user takes an explicit delete action on the Settings screen. A third option would be to store settings information in a database. It looks like other Dat archive metadata is stored in a database but this is another area I haven't investigated deeply. Let me know what you think!

**Comment by brechtpm** [comment]
One possible way to fix this for your project specifically, is to check your entire repo including sources into dat, and than set a `web_root` in [dat.json](https://beakerbrowser.com/docs/apis/manifest.html) pointing to your _site folder.

That obviously doesn't solve the underlying problem you're reporting, but it might be a practical solution for your case.

**Comment by mxhllnn** [comment]
@brechtpm good point. Another approach would be to add a web root field to the settings form. This would enable the user to select different directories for the archive and the web root. Then fall back to setting a default `dat.json` if the file doesn't exist during an update.

**Comment by pfrazee** [comment]
The way that Beaker manages the "staging area" is going to change in 0.8, so the solution might change a little then too. Rather than every dat having an assumed "staging area," we've added a concept of a "workspace" which can be explicitly added by users, and which isn't part of the `DatArchive` APIs. That means that any mutations via the `DatArchive` API such as `.writeFile()` will immediately be published, and `commit()` will be deprecated.

That said, the underlying issue will basically be the same. We don't want to remove the ability to modify the dat.json from the workspace directory, but it does seem like there are certain levels of modification that should be protected against. Perhaps if you try to delete the dat.json, it just auto-restores it from the last good settings.
