### ISSUE TITLE
Database support ?

### ISSUE THREAD

**Issue by lbphp** [beakerbrowser/beaker#864]
Hello,
does the Beaker system provide some kind of database support?

Also, after a quick glance at the docs, i did not find a way to detect user actions.
That may be required for example if i have an e-commerce site.
When an user clicks on the Buy button for a product, i need to receive his request to process the purchase order.

**Comment by pfrazee** [comment]
Not yet! We have some ideas for how to do this, but if you need a central DB, the current solution is to host a service somewhere.

Our goal is something we call "one package," which is the idea that a Dat site will contain all the code for the frontend and the backend code (which would include the DB). Then if somebody wants to run their own instance of the app's DB, they can start up their own backend with the DB.

To do that, we need a backend/DB platform that doesn't exist yet. It might be a blockchain, or it might be a federated cloud hosting system. We'll see.

**Comment by sleepndevelop** [comment]
"which would include the DB" 
so the DB would be replicated to all nodes?

And every node can do updates on it,  and then other nodes will synchronize their db to reflect the updates?

Example: a Dat site is an ecommerce, a buyer purchases 1 unit of a product, the DB gets updated. After then the other nodes should be notified that the product has 1 unit less

**Comment by pfrazee** [comment]
> "which would include the DB"
> so the DB would be replicated to all nodes?

Well, the use-case you're talking about (e-commerce) needs to have a logically centralized DB so that it can apply constraints and backend logic. The way to accomplish that is to either use a server or a blockchain. So when I say the package includes the "backend code including the DB" what I meant was the code for managing the DB. The DB state would be kept in the hosting server/blockchain.

If you aren't doing ecommerce, then you can use Dats to store and distribute data. There's a module called WebDB (https://github.com/beakerbrowser/webdb) which abstracts over that. But Dat & WebDB would never work for ecommerce.
