### ISSUE TITLE
Discussion: Dat DNS TXT records

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#958]
Discussion for https://github.com/beakerbrowser/beaker/wiki/Dat-DNS-TXT-records-with-optional-DNS-over-HTTPS

**Comment by RangerMauve** [comment]
Using the existing DNS over HTTP is nice because it's easier to get it to work in browsers that don't have the DatArchive API. There's more potential to have logic in an extension that handles this as you won't need a way to access DNS entries directly.

Using a TXT entry lines up with what IPFS/IPNS are doing, but I don't think the old method should be fully replaced by this.

**Comment by pfrazee** [comment]
The new proposal still falls back to the .well-known solution.

**Comment by RangerMauve** [comment]
Yeah, but won't people only bother implementing one or the other? If someone goes through the trouble of setting up a DNS TXT record, they won't bother using the `.well_known` approach.

Can DNS over HTTPS be used with fetch?

**Comment by pfrazee** [comment]
In fact I have to push back on the "making things more difficult for other browsers" idea, because, if they can implement `DatArchive` suitably, then they most certainly can access DNS.

**Comment by RangerMauve** [comment]
When I say browsers, I mean the technology available from the browser itself. Specifically, the endeavors being made to [make dat work with vanilla browsers](https://github.com/datproject/discussions/issues/84#issuecomment-382797843).

Though I guess that instead of limiting the protocol, it makes more sense to add functionality to dat-gateway to do the DNS lookups for us. I'll also look into the DNS over HTTPS to see if there's anything web-accessible out there.

**Comment by parfish** [comment]
I have some questions related to this from the perspective of someone who comes from Userland:
1) Is there a place (not called Twitter) to ask dumb questions about Beaker and DAT without bothering busy developers?
2) If you set up a DAT only site is there a way to have a short name (dat://easyname/index.html). i.e. something that looks friendly on the web and can be opened by Beaker?

So far this is the only thing re. Beaker that is confusing this dumb user.

**Comment by webdesserts** [comment]
@parfish Nothing dumb about asking questions! I'd say it's perfectly fine to ask questions on Github, especially if they need a good explanation. @pfrazee and @taravancil aren't the only ones that watch the issue tracker. Other than Github you can also find people on the `#beakerbrowser` irc channel or the `#dat` channel if you have dat specific questions. Although it's a bit newer there's also a [/r/beakerbrowser](https://www.reddit.com/r/beakerbrowser/) subreddit now as well.

As for your question, for now there are two main ways to get a cleaner URL:

1. [Hashbase](https://hashbase.io/) – A free service maintained by the Beaker team that seeds your site to keep it live and gives it a clean URL under their domain. For example my website is hosted at `www-webdesserts.hashbase.io`. Hashbase will also broadcast your site over `http` by default.
2. [Homebase](https://github.com/beakerbrowser/homebase) – If you're willing to go a bit more hands-on you can also set up a "homebase" which will allow you to have more control over your domain names and how they're hosted. In short, a Homebase is your own custom Hashbase and you can you set up a URL like `dat://site.my-domain.com` with it if you're willing to run your own server.

Both of these are nice solutions, but suffer from the downsides mentioned in [the proposal](https://github.com/beakerbrowser/beaker/wiki/Dat-DNS-TXT-records-with-optional-DNS-over-HTTPS). Specifically this one:

> An HTTPS host must be run for each Dat to provide the domain name. This adds a lot of overhead to users (and ruins some of the fun of p2p).

So yeah, currently you can't have a clean URL without also involving HTTPS, which kinda sucks. If the Beaker team decides to implement this proposal, that will mean you can skip the HTTPS server and just use a DNS record.

**Comment by pfrazee** [comment]
Michael’s explanation is on point, I just want to reiterate that in this DEP, it’s possible to have a nice dat name using only DNS.

**Comment by parfish** [comment]
I like the idea of doing this via the dat.json file. 

Just for fun I tried the ".well-known" method on my site, but it's not https (so didn't work).
http://scramblekit.uk/.well-known/dat

The site's DAT address in glorious long-form is here: http://scramblekit.uk/review/scramble-dat/about.html

It's interesting for me since I'm fine with html, php, css and a little editing of js. But I feel very out of my depth with DNS and server configs and the like. 

What I, as a user, would like is: 
Beaker Browser > Library > Select site > Settings > Enter shortname you'd like for your site {at least x chars, no spaces  blah blah)  > check against some DAT database to see if name is currently used > IF already taken choose another shortname OR apply shortname > name gets appended to the DAT shortnames database 

But of course it's a lot more complicated than that (+ security issues etc) behind the scenes. 

@pfrazee -- Great work on Beaker Browser by the way  !!! There's so much going on with censorship and data abuse, and people waking up to the fact that they don't control their stuff ... well, let's say, your timing is very good. 

Thanks both for your help.

**Comment by arni077** [comment]
i dont understand why DatArchive must be supported by the browsers(ie chrome,firefox) in order to use it in apps?

**Comment by pfrazee** [comment]
@arni077 sorry, to use what?
