### ISSUE TITLE
Site unavailable (even with seeds available)

### ISSUE THREAD

**Issue by djbacon** [beakerbrowser/beaker#977]
Operation System: Ubuntu Mate 18.04 (64bit)
Beaker version: Version: 0.8.0-prerelease.5 Electron: 2.0.0-beta.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

A few days ago i encountered strange bug. I don't know what was the reason for this so i will try to tell it in exact order it happened.

I created page using Beaker Browser on my laptop (let's cal it PC 1).
I kept it open and then opened it on another pc (called PC 2) and let it download and set it to Seed forever. Then added to Favorites.
After page fully downloaded i shut down PC 2.
Then i set up dat share on my server (PC 3) and let it fully download.
Then i went to my countryside (telling you this because ip address on PC2 changed changed) and opened that website on PC 2 and it it was trying to locate page and while it was doing that peer count changed to 1 for a half second and then back to 0. It did that a few times and then just displayed "page not found" message.
After several refreshes i set it to "Seed while visiting", removed it from my Library and restarted Beaker Browser. After this page opened without problems and showed 1 peer (as it should). I noticed that page data was not deleted after i set it to Seed while visiting.

Hope this helps.

**Comment by djbacon** [comment]
There were changes after PC 2 shut down.

**Comment by pfrazee** [comment]
Ok so here's my theory:

 1. When you took PC2 to the countryside, you had a connection that lasted long enough to download the updated metadata.
 2. The connection then died before you could download the updated file content.
 3. As a result, when you tried to visit the page, Beaker gave you a 404.
 4. Removing the site from your library probably didn't do anything (unless you cleared your cache) because Beaker keeps dat data in the cache for ~2 weeks.
 5. Restarting Beaker then solved the connection problem and you managed to sync the missing file-content.

🕵️ open and shut case

**Comment by djbacon** [comment]
almost the same happened to PC3 when i returned from countryside. funny thing is that dat-share is on PC3 and it still showed me 404. A few restarts did not do anything. After i removed it from library **and** clicked "Delete downloaded files" page loaded correctly. Beaker Browser was not open on PC3 while i was at countryside and last time i opened Beaker page loaded correctly.

**Comment by pfrazee** [comment]
We had somebody else report an internal file-corruption case recently. Same thing, they had to clear the internal data cache to get it to work. @mafintosh was given the internal data files so he's going to take a look.
