### ISSUE TITLE
Allow selective seeding of Dat's files and/or folders

### ISSUE THREAD

**Issue by ghost** [beakerbrowser/beaker#987]
Rationale:

## Fine-grained control of dat's storage consumption
  I'm currently seeding this dat [dat://dat-cast.hashbase.io/](dat://dat-cast.hashbase.io/), which as you can see is rather large (607.54 MB).
  While reviewing the filesystem in the library I noticed that most of this space was used by a folder called "production-assets". I think it would be very useful for any user to be able to stop seeding this folder after a while, but keep seeding the rest of the files (more recent podcast, compressed/edited/final versions, etc.)

## Opinions, beliefs, moral principles, disturbing content, etc.
Another argument for such a feature would be that, as a user, I would like to decide which content I'm willing to help seeding and spreading. Other peers would still be able to download those files from other peers (if someone is seeding them). 
Additionally, it could be very useful to also allow "stop storing"/removing/blocking some content from a read-only dat local-copy, while still keeping the rest of the content. For the same reasons discussed above.

## Use case
Imagine I'm following some Fritter profile. They share some content I'm not comfortable with.
However, I would like to help the network by sharing everything else.
I could mark the controversial files as (blacklisted) but keep sharing everything else.

## My understanding
As I understand it, both aforementioned features are currently possible if I fork an existing dat. Since I am able to perform write operations to my forked copy. However, I think this implies that I'm not spreading or helping seeding the original dat anymore (maybe I'm wrong.)
Also, when I fork a dat, I won't be receiving any future content from the original dat.
For that reason, I think the two features mentioned above could be very useful and are currently missing in BeakerBrowser.

By the way, all your efforts and results in this project, dat, etc. is AWESOME! Thank you!

**Comment by pfrazee** [comment]
@fejnartal Thanks for the detailed writeup. This idea adds some complexity to the software, but I think it has merit so it's the kind of thing we should consider. (And, yes, you're right about how forking works.)

I'm going to call this the `Selective-share policy`. It would control what files you automatically download and reshare when you're seeding a site, and it would also control what files can be automatically deleted after some time (because they're basically cached). It would need to be a policy, I think, because it would need to describe file-paths or even file-patterns which could apply to files that don't exist yet. (For instance, a Fritter 'selective-share policy' could be "only `/profile.json` and `/posts/*.json`.)

Something like this would break down into three broad tasks:

 1. Executing the selective-share policy internally
 2. Providing the policy controls in Beaker's builtin UIs
 3. Providing APIs to control the policy on a site

1 and 2 are relatively straightforward, though they'd require some heavy dev work (and so will probably not be near-term). 3 gets somewhat more interesting, because you have to manage multiple flows and how to manage the interests of potentially multiple apps. It would certainly be great it Fritter could, on follow, start seeding the profile with a selective-share policy.

**Comment by pmario** [comment]
That's very interesting. ... So analysing blacklisted content, will tell a lot about the user who created the blacklist. 

just some thoughts.

**Comment by fejnartal** [comment]
@pmario I don't think users should be able to know blacklisted content from other users directly.
Of course, probably there are ways to systematically ask for resources to an individual and if they don't have them one could assume they have it blacklisted (but maybe not, and they just didn't request it yet.)

So, no need to be able to read other users "blacklists".
